src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/AdministrationCourtRoomControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/MessagingControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/messages/Message.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/messages/MessageKey.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/MessagingServiceImpl.java, src/main/resources/db/migration/V1_40__message_date_type_update.sql, src/test/java/uk/gov/hmcts/juror/api/moj/service/MessagingServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6691)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=113)
FILE_DATETIME column data type needs updating
In Heritage the Format is YYYYMMDD_HHMISS where HH is hours in 24 hour format 
e.g. 20240325_151025 for 10 minutes and 25 seconds past 3pm on 25th of March 2025
In the new schema we will preserve the data accuracy using a timestamp(8) data type (mapping to LocaDateTime in the backend API)
```
[ ] Yes
[X] No
```
=> As a developer I want to refactor the message table

src/main/java/uk/gov/hmcts/juror/api/moj/domain/Appearance.java
Fixed issue where calculate totals would fail when smart card is null
```
[ ] Yes
[ X] No
```
=> Fixed issue where calculate totals would fail when smart card is null

build.gradle, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/resources/db/jurormanagement/ConfirmJuryAttendance.sql, src/integration-test/resources/db/jurormanagement/JurorsOnTrial.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/ITrialRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorHistoryService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorHistoryServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorHistoryServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6742
- add logic when confirming jury attendances to also generate a jury attendance audit number and apply the same number to all jurors in confirmation batch
- add new helper method to create jury attendance history event
- update queries to retrieve jurors on trials summary data
- update unit tests
- update integration tests
```
[ ] Yes
[X] No
```
=> JM-6742: Generate attendance audit number when confirming Jury Attendance

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
[JM-6937](https://centralgovernmentcgi.atlassian.net/browse/JM-6937)
Addition of check to ensure that a non-attendance day that is in the future cannot be created. If a user attempts to create a non-attendance day for a future date, a BadRequest exception is thrown.
```
[ ] Yes
[x] No
```
=> JM-6937: Fix to non-attendance day feature and associated tests.

src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolHistoryServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6933)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=187)
When I click history on the pool overview page as a court user i get redirected to the pool records screen.
When I do the same action as a bureau user I can see the correct history
```
[ ] Yes
[X] No
```
=> Pool Overview -- When i click history as a court user I get redirected to the pool request screen

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorExpenseControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/PanelControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/TrialControllerITest.java, src/integration-test/resources/db/trial/Panel.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/AppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6951
- remove findByJurorNumber() JPA method from Appearance Repository
- update code to use findByJurorNumberAndAttendanceDate() instead
- refactor AppearanceRepository to make findByJurorNumberAndAttendanceDate() return an Optional object (to avoid null pointer exceptions)
- refactor/optimise logic so Panel repository query is only invoked once instead of twice for the "adding panel members" user journey
- update tests
```
[ ] Yes
[X] No
```
=> hotfix/JM-6951: Adding panel members fails when a juror has more than one attendance

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7016
- include juror status of panel when confirming attendance - jurors on a panel are not yet on a jury/trial so cannot be confirmed by jury attendance and therefore need to be confirmed as jurors in waiting
- update tests
```
[ ] Yes
[X] No
```
=> hotfix/JM-7016: Confirm attendance for Panelled jurors

src/main/java/uk/gov/hmcts/juror/api/juror/domain/JurorResponseQueries.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6975
This page was checking `superurgent == false` for several checks, which since superurgent got removed and is now always null was failing all the time.
```
[ ] Yes
[X] No
```
=> Bug (JM-6975) fix superurgent nulls breaking response report listing

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordController.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/AppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7119)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=243)
**Steps:**
Create attendance and expenses on juror record
Reassign to another pool
**Outcome:**
Attendance records are cleared
```
[ ] Yes
[X] No
```
=> Reassigning a juror to new pool clears attendance records.

src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/CertificateOfAttendanceListRepositoryImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7116)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=249)
Fixed issue where last name concatenation was incorrect for name search
```
[ ] Yes
[X] No
```
=> Document name search only searches first name, not last name or full name

src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/TestConstants.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7118)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=252)
Fixed an issue where expense approval could not work if you had appearances in multiple pools at the same court 
```
[ ] Yes
[X] No
```
=> Reassigning a juror to new pool clears expense records.

src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/PoolMemberFilterRequestQuery.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/ActivePoolsCourtRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolRepositoryImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolRepositoryImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7132)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=256)
When trying to filter on an active pool it kicks you out to pool requests 
```
[ ] Yes
[X] No
```
=> UAT - when sorting by name in an active pool it kicks you back to pool requests

src/integration-test/resources/db/MessagingControllerITest_postSearchSetup.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/MessageTemplateRepositoryImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/repository/MessageTemplateRepositoryImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7147)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=260)
Reassign a juror from pool 1 to pool 2
Search by pool 1 in export contact details
Expected:
juror does not appear in search for pool 1
Actual:
juror appears in search for pool 1 with status ‘Reassigned’
```
[ ] Yes
[X] No
```
=> Jurors who have been reassigned pools appear in export contact details search by old pool number

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/MessagingControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/messages/ExportContactDetailsRequest.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/request/messages/ExportContactDetailsRequestTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7171) and ⁠[JM-7170](https://centralgovernmentcgi.atlassian.net/browse/JM-7170)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=283)
As they use this for mail merges, this is an issue
modernisation
!image-20240430-103804.png|width=1322,height=254,alt="image-20240430-103804.png"!
heritage
!image-20240430-103826.png|width=1490,height=265,alt="image-20240430-103826.png"!
```
[ ] Yes
[X] No
```
=> Contact details export returns "null" for empty fields

src/main/java/uk/gov/hmcts/juror/api/moj/domain/authentication/UserDetailsDto.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7187)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=287)
Insert a last login date/time in the database for existing user(s)
Log in as a system admin user
Navigate to the Users screen
Verify the last login date is displayed correctly:
!image-20240501-091504.png|width=1422,height=740,alt="image-20240501-091504.png"!
```
[ ] Yes
[X] No
```
=> Last Login Date incorrectly displayed on System Admin > Users screen

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/UserControllerITest.java, src/integration-test/resources/db/administration/createUsers.sql, src/integration-test/resources/db/administration/teardownUsers.sql, src/integration-test/resources/db/mod/truncate.sql, src/main/java/uk/gov/hmcts/juror/api/config/JpaEnversConfig.java, src/main/java/uk/gov/hmcts/juror/api/config/SecurityConfig.java, src/main/java/uk/gov/hmcts/juror/api/moj/audit/AuditorResolver.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/User.java, src/main/resources/db/migration/V1_65__create_users_audit_table.sql
https://centralgovernmentcgi.atlassian.net/browse/JM-6600
- Enable JPA auditing in the SecurityConfig class
- Implement AuditorAware interface to resolve auditing user properties (created_by and updated_by) using the username form the current SecurityContext
- Update User entity to enable envers auditing and add new properties for created_by and updated_by
- add flyway script to create new audit tables and update existing users table
```
[ ] Yes
[X] No
```
=> task/JM-6600: Log changes to users table (users_audit)

src/main/java/uk/gov/hmcts/juror/api/bureau/controller/BureauAuthenticationController.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauAuthenticationServiceImpl.java
N/A
- Add activeUserType from the new authentication by email, to the old authentication mechanism for compatibility purposes.
```
[ ] Yes
[x] No
```
=> add activeUserType to old authentication mechanism

src/main/java/uk/gov/hmcts/juror/api/juror/domain/CourtLocation.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/UserServiceModImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7201)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=292)
Log in as a system admin
select a court user with assigned courts
click assign courts
you should not see court locations that are already assigned
!image-20240502-093829.png|width=1011,height=837,alt="image-20240502-093829.png"!
!image-20240502-093856.png|width=1011,height=837,alt="image-20240502-093856.png"!
```
[ ] Yes
[X] No
```
=> As a system admin, court locations appear that are already assigned

src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/JurorManagementRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/poolmanagement/JurorManagementServiceImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7046
Currently, the validate movement API doesn't allow postponement for jurors who are deferred. In this case, we need to postpone from deferral maintenance, where everyone is deferred, so add a flag to skip this check.
```
[ ] Yes
[X] No
```
=> Chore (JM-7046) add check exception for validating postponement from deferral maintenance

src/integration-test/resources/db/jurorresponse/RetrieveJurorResponses.sql, src/main/java/uk/gov/hmcts/juror/api/moj/service/summonsmanagement/JurorResponseRetrieveServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/summonsmanagement/JurorResponseRetrieveServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7264)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=313)
I have set SEARCH_RESULT_LIMIT_BUREAU_OFFICER and SEARCH_RESULT_LIMIT_TEAM_LEADER both to have value 100
This has not affected the search results that are returned
!image-20240509-141955.png|width=1270,height=735,alt="image-20240509-141955.png"!
!image-20240509-142021.png|width=342,height=43,alt="image-20240509-142021.png"!
```
[ ] Yes
[X] No
```
=> Number of search results not limited by setting SEARCH_RESULT_LIMIT_* in app_setting

src/main/java/uk/gov/hmcts/juror/api/bureau/controller/ResponseDeferralController.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/DeferralRequestDto.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7251)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=311)
When updating jurors record to accept/reject a referral request it will fail with the error {{“Date cannot be earlier than orginal summons"}} - Even when the date is not earlier than original summons
```
[ ] Yes
[X] No
```
=> Granting or refusing deferral requests as a Bureau user is failing

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordController.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/PoliceCheckStatusDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7297)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=333)
PNC scheduler batch job reports MAX_RETRIES_EXCEEDED count as 0 even when there are jurors updated to that status. It counts them in the {{TOTAL_WITH_STATUS_ERROR_RETRY_OTHER_ERROR_CODE}}
```
[ ] Yes
[X] No
```
=> PNC batch job does not count meta_data correctly

src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/expense/ExpenseType.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/FinancialAuditDetails.java, src/main/resources/db/migration/V1_77__removed_reapproval_edit_expense_type.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7290)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=337)
The {{FinancialAuditDetails}} entity has a type property which maps to an enum
{{REAPPROVED_EDIT}} is not needed and didn’t exist in Heritage so can be removed
the database constraint will also need updating via flyway to remove this value
```
[ ] Yes
[X] No
```
=> As a developer I want to remove REAPPROEVED_EDIT as a financial audit type

src/main/resources/db/migration/V1_82__summons_search_optimisations.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7312)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=346)
The “Summons Reply Search” flow is failing PVT as page load times takes longer then 1.5 seconds 95% of the time.
Biggest offender seems to be when searching by last name.
Need to look at better index’s for the Juror Response table maybe fixed by updates to JM-7311
!image-20240516-165445.png|width=1322,height=468,alt="image-20240516-165445.png"!
```
[ ] Yes
[X] No
```
=> Improve the performance of the "Summons reply search"

src/integration-test/java/uk/gov/hmcts/juror/api/bureau/controller/BureauOfficerAllocatedRepliesControllerTest.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorDigitalResponseRepositoryModImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7386)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=364)
When you create a new user with no replies assigned the user does not appear in assign replies as a bureau user
```
[ ] Yes
[X] No
```
=> UAT - Users only show up in Assign replies if they have at least one reply assigned

src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolQueries.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7388)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=366)
This appears to be because it looks for jurors that are both owned and not owned by the bureau
```
[ ] Yes
[X] No
```
=> WeeklyComms does not pick up any jurors who should receive the comms

build.gradle, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/MessagingControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/juror/service/ExcusedCompletedCourtCommsServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolQueries.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7382)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=374)
When sending an excusal email, the job duplicates the email in notify for both English and Welsh emails. This works as expected for SMS
!image (9).png|width=690,height=196,alt="image (9).png"!
!image (8).png|width=1291,height=637,alt="image (8).png"!
```
[ ] Yes
[X] No
```
=> Cronbatch excusal completed court comms sends excusal emails twice

src/main/resources/db/migration/V1_94__alter_system_params_table.sql
https://centralgovernmentcgi.atlassian.net/browse/JM-7307
- increase the column length of sp_value in the system_parameter table (to match NLE)
```
[ ] Yes
[X] No
```
=> task/JM-7307: Create V1_94__alter_system_params_table.sql

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/PanelMembersStatusReportITest.java, src/integration-test/resources/db/mod/reports/PanelMembersStatusReportITest_Typical.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/reports/request/StandardReportRequest.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/AbstractReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/DataType.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/PanelMembersStatusReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/AbstractReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/DataTypeTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/PanelMembersStatusReportTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7328)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=361)
*Acceptance criteria*
 
·       Jury list
·       Ballot cards
·       Panel list (summary)
·       Panel list (detailed)
·       Panel members status report
#* Back (Hyperlink)
#* *Panel member status report* (Header)
#* Print (Tab)
#* *Trial number*
#* *Names*
#* *Courtroom*
#* *Judge*
#* *Report created*
#* *Time created*
#* *Court name*
#* Panelled (count)
#* Empanelled (count)
#* Not Used (count)
#* Challenged (not used)
#* Returned jurors (count)
#* Juror number
#* Panel status
```
[ ] Yes
[X] No
```
=> As a court officer I want to generate a Panel member status report (BE)

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6969)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=403)
Steps to reproduce (also commented)
* Check in juror to mark them down as listed as attending
* Click change link
* Click ‘delete attendance and mark as absent’
* Click yes on confirmation screen
* Go to juror record and check attendance table, 0 absences.
```
[ ] Yes
[X] No
```
=> Mark as absent doesn't work from record attendance

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/LetterControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/LetterBase.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/PrintDataServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/AbstractLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/ConfirmLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/DeferralDeniedLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/DeferralLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/ExcusalDeniedLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/ExcusalLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/LetterBaseTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/PostponeLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/RequestInfoLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/SummonsLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/SummonsReminderLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/WithdrawalLetterTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6312)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=393)
I ran the tests over the weekend and noticed this test failed, citing “can not generate a letter on a weekend”. [~accountid:62306f3e50cceb0070797d12] is that correct? Should the bureau be prevented from generating letters at the weekend?
!image-20240226-102702.png|width=843,height=411!
```
[ ] Yes
[X] No
```
=> Cannot generate a letter on a weekend (Bureau)

src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolQueries.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7378)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=411)
This needs looking at in potentially a couple of areas
* Seems to be looking for a juror_pool owned by bureau but that also has a transfer to court date set
* Also seems to be filtering on transfer time but we don’t actually store a time anymore just a date
Probably needs a full rework as there will be more than this
```
[ ] Yes
[X] No
```
=> Sent to court comms does not pick up any valid requests as the logic is incorrect

src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauBacklogAllocateServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolQueries.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsRequestInformationLetterServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/juror/service/JurorServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7380)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=415)
Believe this may be because the code looks for a completion date in the last 2 days but also a status of responded, I don’t think it’s possible for both of these to be true.
```
[ ] Yes
[X] No
```
=> Cronbatch excusal completed court comms does not pick up completed jurors

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/TrialControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/TrialController.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/trial/TrialSearch.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/ITrialRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/ITrialRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/TrialControllerTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7437)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=419)
Further changes needed to endpoint to get a list of trials, [GET /api/v1/moj/trial/list|http://localhost:8080/swagger-ui/index.html#/Trial%20Management/getTrials].
The trial selection page needs all active trials returned, the current endpoint is capped to 25.
!image-20240530-085711.png|width=50%,alt="image-20240530-085711.png"!
Discussed with [~accountid:712020:c60a5691-915b-44ae-af30-91be5d42156c] to add a query param for showAll=true which will remove the limit of 25 items being returned.
```
[ ] Yes
[X] No
```
=> Update Trials List API to allow for no cap on return limit

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordController.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorAttendanceDetailsResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorDetailsCommonResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/utils/SecurityUtil.java, src/test/java/uk/gov/hmcts/juror/api/TestUtils.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7426)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=%pullRequestNumber%)
For court officers that have primary and satellite courts we need to make sure they have the correct relationship for what you can do when logged in as either the primary or satellite:
you can do and see everything for the other courts in your court stack except for the following:
* trial management
* attendances
* expenses
Attached is a spreadsheet the list shows in red the areas that need updating the second tab details what reports show satellite court data 
```
[ ] Yes
[X] No
```
=> As a system I need to make sure that satellite and primary courts work correctly

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/grouped/UnpaidAttendanceSummaryReportITest.java, src/integration-test/resources/db/mod/reports/UnpaidAttendanceSummaryReportITest_typical.sql, src/main/java/uk/gov/hmcts/juror/api/moj/report/grouped/UnpaidAttendanceSummaryReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/grouped/UnpaidAttendanceSummaryReportTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6491)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=436)
|JMRSM 15:|The system shall enable officers to generate an unpaid attendance summary report|
|Requirement Description|The system shall enable officer to generate an unpaid attendance summary reprort.
 
#* Date from
#** Must be a real date
#* Date to
#** Must be a real date
#** Must be after attendance from
#* Date from
#* Date to
#* Total unpaid attendances
#* Report created
#* Time created
#* Court name
#* Juror number (hyperlink)
#* First name
#* Last name
#* Total (per day)
Dev note
The list contain juror with unpaid attendances for that court for the days in the date range|
|Owner|Product Owner|
|Additional Details|*Existing …
=> As a jury officer I need to be able to generate a unpaid attendance summary report (BE)

src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7456)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=442)
The juror number is being used in place of the pool number on the unpaid attendance screen, which is causing failures elsewhere.
```
[ ] Yes
[X] No
```
=> Juror number being used in place of pool number on Unpaid Attendance

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/PoolRatioReportITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/DataType.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/PoolRatioReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/PoolRatioReportTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6527)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=445)
|JMRSM 18:|The system shall enable the Bureau officers to generate a pool ratio report|
|Requirement Description|The system shall enable the bureau officer to generate a pool ratio report.
 
#* Date from (date picker)
#** Must be a real date
#* Date to (date picker)
#** Must be a real date
#* Text filter
#** Filter using name or location code
#* Select all button
#* List of all courts wit a button to select each individually
#* Date from
#* Date to
#* Report created
#* Time created
#* Court
#* Requested (1)
#* Deferred (2)
#* Summoned (3)
#* Supplied (4)
#* Ratio 1 (3-2) /(1-2)
#* Ratio 2 (3-2) /(4-2)
|Owner|Product Owner| …
=> As a Bureau officer I want to generate a pool ratio report (BE)

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/AuditControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/AuditController.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/audit/JurorAuditService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/audit/JurorAuditServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/AuditControllerTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7475)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=455)
In order to access the pool audit report from the FE Attendance tab, we need to provide a list of audit numbers for the user to select from.
A new endpoint needs created to provide this information.
!image-20240604-122126.png|width=2220,height=986,alt="image-20240604-122126.png"!
[https://www.figma.com/design/YvdqYIgmd4q0VLg7Npw9O4/Reports-(SPEC)?node-id=565-74394&t=QsWJYvA1ihlIPsRO-4|https://www.figma.com/design/YvdqYIgmd4q0VLg7Npw9O4/Reports-(SPEC)?node-id=565-74394&t=QsWJYvA1ihlIPsRO-4|smart-link] 
```
[ ] Yes
[X] No
```
=> Pool attendance audit report number list (BE)

src/main/java/uk/gov/hmcts/juror/api/moj/domain/Appearance.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7488)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=462)
Cannot invoke "uk.gov.hmcts.juror.api.moj.enumeration.AttendanceType.getPayAttendanceType()" because the return value of "uk.gov.hmcts.juror.api.moj.domain.Appearance.getAttendanceType()" is null
!Screen Recording 2024-06-05 at 18.14.48.mov|width=3112,height=1678,alt="Screen Recording 2024-06-05 at 18.14.48.mov"!
```
[ ] Yes
[X] No
```
=> When viewing expense records created as part of the End Trial and Confirm Attendance flow a technical error is displayed

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/PoolSelectionReportITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/reports/request/StandardReportRequest.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/DataType.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/AvailableListByPoolReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/PoolSelectionListReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/AvailableListByPoolReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/PoolSelectionReportTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7499)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=464)
he system shall enable the court or bureau officer to generate a pool selection list.
 
#* The system shall error if no pool number entered.
#* Pool number (hyperlink)
#* Court name
#* Pool stage
#* Pool status
#* Pool type
#* Service start date
#* Pool number
#* Pool type
#* Service start date
#* Report created
#* Time created
#* Court name
#* Juror number (hyperlink)
#* First name
#* Last name
#* Postcode
#* Disqualified on selection
```
[ ] Yes
[X] No
```
=> As as Bureau or court officer I need to generate a pool selection list (BE)

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/trial/TrialSummaryDto.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7406)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=458)
Steps:
* create a trial with any date
* edit the trial and see todays date instead of the original
!image-20240524-093550.png|width=819,height=403,alt="image-20240524-093550.png"!
!image-20240524-093601.png|width=1002,height=852,alt="image-20240524-093601.png"!
```
[ ] Yes
[X] No
```
=> When editing a trial the trial date does not show the date originally set, shows todays date instead

charts/juror-api/Chart.yaml, charts/juror-api/values.yaml, src/main/java/uk/gov/hmcts/juror/api/moj/service/JwtServiceImpl.java, src/main/resources/META-INF/additional-spring-configuration-metadata.json, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/juror/api/moj/service/JwtServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/utils/TestConstants.java
Updated jwt expiry to be a long instead of a string
```
[ ] Yes
[X] No
```
=> Updated jwt expiry to be a long instead of a string

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/UndeliverableResponseControllerITest.java, src/integration-test/resources/db/UndeliverableResponseController_createInitialPoolRecords.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/UndeliverableResponseController.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorHistoryService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorHistoryServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/UndeliverableResponseService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/UndeliverableResponseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/utils/JurorPoolUtils.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/UndeliverableResponseServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7589)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=500)
Bureau Only (all bureau officers)
In the summons reply module we need a new heading Mark as undeliverable
The system shall allow the officer to enter or scan in Jurors and build up a list with the following columns:
Juror number (hyperlink)
First name
Last name
Address
Postcode
Court
they system shall allow the officer to submit the jurors to mark an undeliverable
The system shall display a a holding screen to confirm the action. ‘this will mark X jurors as undeliverable status’ 
the system shall allow the juror to continue and display the success banner ‘x number of jurors marked as undeliverable’
**Does this PR introduce a …
=> Mark as undeliverable (bulk) (BE)

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerITest.java, src/integration-test/resources/db/JurorRecordControllerITest_getJurorDetailsFiltered_typical.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordController.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorPoolDetailsDto.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7588)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=503)
Bureau Only (all bureau officers)
In the summons reply module we need a new heading Mark as undeliverable
The system shall allow the officer to enter or scan in Jurors and build up a list with the following columns:
Juror number (hyperlink)
First name
Last name
Address
Postcode
Court
they system shall allow the officer to submit the jurors to mark an undeliverable
The system shall display a a holding screen to confirm the action. ‘this will mark X jurors as undeliverable status’ 
the system shall allow the juror to continue and display the success banner ‘x number of jurors marked as undeliverable’
**Does this PR introduce a …
=> Mark as undeliverable (bulk) (FE)

src/main/java/uk/gov/hmcts/juror/api/moj/service/EditPoolServiceImpl.java, src/main/resources/db/migration/V1_140__pool_history_length_update.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7180)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=512)
It shows the wrong time and message in pool history when adding a comment to a pool edit
!image-20240430-150013.png|width=451,height=276,alt="image-20240430-150013.png"!
```
[ ] Yes
[X] No
```
=> UAT - It shows the wrong time and message in pool history when editing the pool and adding a comment

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/expense/SimplifiedExpenseDetailDto.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7614
Updated the JSON formatter for the audit timestamp on expenses to use ISO rather than nearly ISO.
```
[ ] Yes
[X] No
```
=> Fix (JM-7614) update expense LocalDateTime formatter to ISO

src/main/resources/db/migration/V1_144__content_store_update.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7639)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=525)
*SELECT*  *NEXTVAL*(*'juror_mod.print_file_count'*) *INTO* v_revision;
*SELECT*   *NEXTVAL*(*'juror_mod.payment_file_count'*)
  *INTO* v_revision;
*INSERT* *INTO* juror_mod.content_store(request_id, document_id, file_type, *data*)
    *VALUES* (v_revision,p_File_Name,*'PAYMENT'*,c_lob);
 
Primary Key for content store should be a composite key between requestId and file type
```
[ ] Yes
[X] No
```
=> PAYMENT_JOB fails

src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorResponseCommonRepositoryModImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7474
Added condition to join to include active juror_pool records only.
```
[ ] Yes
[X] No
```
=> Response shows in summons response search twice when juror is reassigned to a new pool

src/main/resources/db/migration/V1_148__perfomrance_job_update.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7649)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=536)
When running the Performance Stats scheduled tasks, not all the required tables (such as third party) are being updated.
```
[ ] Yes
[X] No
```
=> Performance Stats not updating the correct tables

src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsNotifyPayLoadServiceImpl.java, src/main/resources/db/migration/V1_153__payment_job_update.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7658)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=539)
When writing to the content_store table, the request_id should be the sole primary key column (unique constraint).
Make sure the relevant procedures use the content_store_seq when generating unique IDs to insert in to the request_id field
```
[ ] Yes
[X] No
```
=> Payment files to clob using wrong sequence

src/main/java/uk/gov/hmcts/juror/api/moj/domain/jurorresponse/JurorResponseAuditMod.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/jurorresponse/JurorResponseAuditModKey.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorResponseAuditRepositoryMod.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7640
Fixed issue where the audit class was not populating the created field
```
[ ] Yes
[x] No
```
=> hotfix - Changing status of response sets CHANGED date to NULL on juror_response_aud

src/main/java/uk/gov/hmcts/juror/api/moj/service/letter/court/CourtLetterPrintServiceImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7652
Changed message from reissued <Letter> to Print <letter> as it was misleading when issuing letters.
```
[ ] Yes
[x] No
```
=> Hotfix - Juror History - history mentioning 'reissued' letters when they're initial

src/main/java/uk/gov/hmcts/juror/api/moj/domain/PendingJuror.java, src/main/resources/db/migration/V1_155__update_pending_juror.sql
https://centralgovernmentcgi.atlassian.net/browse/JM-7673
- Allow support for migrated data which can contain nulls for pending_juror.dob
```
[ ] Yes
[X] No
```
=> task/JM-7673: Update PendingJuror - Drop not null constraint (DoB)

src/main/java/uk/gov/hmcts/juror/api/moj/controller/MessagingController.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7669)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=551)
Attempting to export contact details via juror number currently doesn’t work. Nothing happens when a csv file is expected to be downloaded. All other options work as expected.
```
[ ] Yes
[X] No
```
=> Export contact details via juror number not working

src/main/resources/db/migration/V1_158__updated_username_length.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7529)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=558)
username field in users and user_roles needs extending to 25 chars
```
[ ] Yes
[X] No
```
=> Update users and user_roles tables

build.gradle, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/LetterBase.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/ConfirmLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/DeferralDeniedLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/DeferralLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/ExcusalDeniedLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/ExcusalLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/PostponeLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/RequestInfoLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/SummonsLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/SummonsReminderLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/WithdrawalLetter.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/ConfirmLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/DeferralDeniedLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/DeferralLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/ExcusalDeniedLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/ExcusalLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/LetterBaseTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/LetterTestUtils.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/PostponeLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/RequestInfoLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/SummonsLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/SummonsReminderLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/WithdrawalLetterTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7736)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=577)
On the addresses on the bulk print letters from the Bureau in the new modernised app there is a difference in the spacing, this is because we are populating the bulk print data as per the spec for the Xerox interface but that spec didn't cover the shuffling of the address/postcode data that was introduced into Heritage in 2019 as a result of an issue in Juror Digital that required address4 (town) to be not null.
 
This means that in a worst case scenario where the address has rows missing the address field will look like the below:
 
e.g.
 
!file:///C:/Users/LIAM~1.MUR/AppData/Local/Temp/msohtmlclip1/01/clip_image002.gif|thumbnail …
=> When there is lines missing from an address we need to be able to shuffle the address lines so there is no gaps in the bulk print

src/integration-test/java/uk/gov/hmcts/juror/api/bureau/controller/BureauOfficerAllocatedRepliesControllerTest.java, src/integration-test/resources/db/BureauOfficerAllocateRepliesService_BacklogData.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorDigitalResponseRepositoryModImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7783
Updated to filter out  inactive users for the assign replies screen
```
[ ] Yes
[ x] No
```
=> hotfix/JM-7783 Duplicate bureau users showing in assign response list

src/main/resources/db/migration/V1_159__pnv_view_uppercase_postcode.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7767)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=582)
The Production environment needed to be updated to force the postcode field to be uppercase in juror_mod.require_pnc_check_view
Create a flyway script to align lower environments
```
[ ] Yes
[X] No
```
=> update require_pnc_check_view to force postcode values to be uppercase

src/main/java/uk/gov/hmcts/juror/api/juror/service/ExcusedCompletedCourtCommsServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/juror/service/MessagesServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/CourtRegionModRepository.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7770)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=584)
This will mean the database insert order doesn't matter anymore
```
[ ] Yes
[X] No
```
=> Update notify code so it orders the court_region table on fetch

src/main/resources/db/migration/V1_160__update_utilisation_to_include_complete_status.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7777)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=583)
following the fix for [[JM-7772] Add juror status 13 to the utilisation report code to include completed jurors - Jira (atlassian.net)|https://centralgovernmentcgi.atlassian.net/browse/JM-7772] we need to cascade this fix into the test environments
```
[ ] Yes
[X] No
```
=> Cascade utilisation juror status 13 fix to the test environments

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/messages/JurorToSendMessageBase.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/MessageTemplateRepositoryImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/repository/MessageTemplateRepositoryImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7764)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=591)
the juror hyperlink is inconsistent some times it works other times it fails and says juror not found:
!image-20240713-141208.png|width=2013,height=609,alt="image-20240713-141208.png"!
```
[ ] Yes
[X] No
```
=> Messaging juror hyperlink not always working says juror not found

src/main/java/uk/gov/hmcts/juror/api/juror/domain/WelshCourtLocation.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/LetterBase.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/ConfirmLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/DeferralDeniedLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/DeferralLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/ExcusalDeniedLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/ExcusalLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/PostponeLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/RequestInfoLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/SummonsReminderLetter.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/WithdrawalLetter.java, src/main/resources/db/migration/V1_161__update_welsh_court_court_name.sql, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/ConfirmLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/DeferralDeniedLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/DeferralLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/ExcusalDeniedLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/ExcusalLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/LetterTestUtils.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/PostponeLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/RequestInfoLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/SummonsReminderLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/WithdrawalLetterTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7751)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=586)
In welsh language we say in Cardiff in the court name we need to change this to just the welsh court name for the bi lingual summons and summons reminders.
```
[ ] Yes
[X] No
```
=> Remove the in in-front of the welsh court name for bi lingual summons

src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/trial/TrialDto.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7792)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=592)
Trials created before go-live weekend that are now not accessible - T20210487/0490 for Croydon. " issues;
1 - when you click on the trial is says page not found
2 - although the name was input in heritage on Friday, it is now saying that the defendant name is exceeding 16 characters
Heritage database supported up to 30 chars for trial.description
Modernised database supports 50 chars for trial.description
Backend API  supports 50 chars for Trial entity, description property
Front end is restricting to 16 chars - please update to match DB/BE
```
[ ] Yes
[X] No
```
=> Existing trials not accessible post migration

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorDetailsResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorOverviewResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/Juror.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/validation/ValidationConstants.java, src/main/resources/db/migrationv2/V2_2__reasonable_adjustments_message_length_update.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7766)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=585)
After a data fix only the reasonable adjustment code is displaying need to also display the message on the juror record and reports
```
[ ] Yes
[X] No
```
=> Reasonable adjustment message not displaying on juror record or reports

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/ExcusalResponseControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/ExcusalResponseServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/ExcusalResponseServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7815
Update to allow juror to be excused when marked as having a paper response but it no longer is in the database or has never been entered
```
[ ] Yes
[x ] No
```
=> hotfix/JM-7815 Bureau or court are unable to process an excusal

infrastructure/test.tfvars
https://centralgovernmentcgi.atlassian.net/browse/JM-7890
Increase test db size (change is to align with change made manually by platOps) when DB went into 'read-only' mode
```
[ ] Yes
[x] No
```
=> Increase test db size

src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7895)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=640)
Expenses showing a "£0" Balance - Payment capped at £64.95 after 10 days. Unable to authorise payments
```
[ ] Yes
[X] No
```
=> Expenses long day flag not updated when a attendance is added in the past (future attendances should get updated)

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/CreatePoolControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/domain/PoolCreateITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementController.java, src/main/java/uk/gov/hmcts/juror/api/moj/exception/MojException.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolCreateServiceImpl.java, src/main/resources/db/migrationv2/V2_13__summoning_updates.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7860)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=641)
Its put a pool flag on there because it thinks someone else is using this data. How do we remove this as we used to do it locally?
Pools effected
479240903
424240903
CW I checked the voters_lock on the court location table @ 22:50,  court 411 is locked, all other courts are unlocked. I suggest ask the Bureau to try again.
UPDATE 18/07 - This has not worked
```
[ ] Yes
[X] No
```
=> Pool request received after go live, however wont create it

src/main/java/uk/gov/hmcts/juror/api/moj/service/DeferralResponseServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7863)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=638)
In Deferral maintenance, removing a Juror from a pool that has already been moved to the court puts the Juror in “no mans land”
```
[ ] Yes
[X] No
```
=> Refusing a juror in Def Maintenance If refusing a juror in Def Maint

src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7939)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=652)
org.hibernate.NonUniqueResultException: Query did not return a unique result: 2 results were returned
at org.hibernate.query.spi.AbstractSelectionQuery.uniqueElement(AbstractSelectionQuery.java:581)
at org.hibernate.query.spi.AbstractSelectionQuery.getSingleResult(AbstractSelectionQuery.java:565)
at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:223)
at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:92)
at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:152)
at …
=> When summoning Jurors a non-unique result error can be returned

src/main/resources/db/migrationv2/V2_18__update_t_history_code_AJUR_template.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7813)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=660)
The Juror history screen shows links to trials and attendance audits but the URL points to financial-audit. This needs updating on the FE to point to correct URL.
!image-20240716-170302.png|width=932,height=780,alt="image-20240716-170302.png"!
```
[ ] Yes
[X] No
```
=> Juror history links need updating

build.gradle, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/AppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7904)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=661)
Adding an attendance on a day a juror was absent outputs this error message
!Screenshot 2024-07-24 at 11.14.53.png|width=1089,height=518,alt="Screenshot 2024-07-24 at 11.14.53.png"!
+*Fix Applied*+
Updated add attendance day to check for pre-existing attendances and if one exists throw an error indicating such
```
[ ] Yes
[X] No
```
=> Wrong error message when adding attendance on absent day

src/main/java/uk/gov/hmcts/juror/api/moj/service/DeferralResponseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/ExcusalResponseServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/ExcusalResponseServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7966)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=675)
Jurors remaining in a summoned status when an excusal is refused. The Juror should go into a "Responded" status.
This logic was missing from the code. Needs an update to put them in "Responded" to ensure they get the confirmation pack.
Can we see how many jurors with a refused excusal/2nd deferral are in a "summoned state". We need these to be updated so the confirmation letter can go out.
The same applies for deferral denied
```
[ ] Yes
[X] No
```
=> Jurors remaining in a summoned status when an excusal is refused. The Juror should go into a "Responded" status.

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorPaperResponseDetailDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorPaperResponseServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7952)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=666)
The date always gets displayed as todays date.
```
[ ] Yes
[X] No
```
=> Summons processed on date not correct on the summons reply view

src/main/java/uk/gov/hmcts/juror/api/moj/repository/AppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/AppearanceCreationService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/AppearanceCreationServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolRequestServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8001)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=681)
Expense Audit Report - When an appearance is created, then deleted, then created again we have duplicate audit entries for the same day. When trying to access the audit report it will not load and defaults to the "Sorry technical error" screen.
01/08 344513805 - Juror number example
Ben applied a data fix to correct the initial issue -
Code fix required
```
[ ] Yes
[X] No
```
=> Expense Audit Report - When an appearance is created, then deleted, then created again we have duplicate audit entries for the same day

build.gradle, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/CompleteServiceControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorExpenseControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/PanelControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/TrialControllerITest.java, src/integration-test/resources/db/trial/Trial.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/trial/PanelController.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/AppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/PanelRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/CompleteServiceService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/CompleteServiceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/utils/RepositoryUtils.java, src/main/java/uk/gov/hmcts/juror/api/validation/ResponseInspectorImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7964)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=682)
Class: TrialServiceImpl
Method: {{returnJury}}
A jury attendance audit number is applied but the trial number is not added to the appearance record (which it should be)
+*Other Fixes Applied:*+
* Updated panel logic to include loc_code filters
* Updated panel & trial logic to use transaction rejecting all database actions un error
* Added new errors when you create/edit a trial using a courtroom or judge that does not belong to that court location 
```
[ ] Yes
[X] No
```
=> Returning a jury doesn't set the trial number on appearance

src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauBacklogAllocateServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauOfficerAllocatedRepliesServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/jurorresponse/CombinedJurorResponse.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/IJurorCommonResponseRepositoryModImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorDigitalResponseRepositoryModImpl.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/BureauBacklogAllocateServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7899)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=700)
Your Work/To Do is showing 18 Jurors, but "Assign Replies" shows 20 
The user has got 20 jurors assigned with status of "TODO" in juror_response table.
!image-20240724-093051.png|width=466,height=379,alt="image-20240724-093051.png"!
!image-20240724-093058.png|width=780,height=649,alt="image-20240724-093058.png"!
Akik has done some initial analysis. The 2 extra jurors(440406091 & 347411804) were transferred to court(before migration) and has got owner other than 400. Code should apply a filter before showing the count.
```
[ ] Yes
[X] No
```
=> INC2529995 - Mismatch in figures between Allocated work from 'Assign Replies' (20) and user's queue to process (18) [HMCTS Ref INC5632895]

src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorDigitalResponseRepositoryModImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7899)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=703)
Fixed issue where total assigned to each bureau user still accounted for transferred  jurors
```
[ ] Yes
[X] No
```
=> Fixed issue where total assigned to each bureau user still accounted for transferred  jurors

src/main/java/uk/gov/hmcts/juror/api/moj/controller/LetterController.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/ReissueLetterServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/letter/ReissueLetterServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8055)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=704)
INC2536487 - When reprinting reminders, the user get a error message - unable to reprint for selected jurors [HMCTS Ref INC5634218]
When reprinting reminders, the user get a error message - “Unable to reprint letters for the selected jurors”.
It is happening when trying to select all Juror records in a pool (451240901) and then send out a reminder letter. 
Error in the log:
{"timestamp":"2024-07-30 10:40:01","message":"*eq(null) is not allowed. Use isNull() instead*"}
```
[ ] Yes
[X] No
```
=> INC2536487 - When reprinting reminders, the user get a error message - unable to reprint for selected jurors [HMCTS Ref INC5634218]

src/main/resources/db/migrationv2/V2_23_message_template.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8057)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=707)
!image-20240814-112042.png|width=1727,height=273,alt="image-20240814-112042.png"!
!image-20240814-112111.png|width=692,height=499,alt="image-20240814-112111.png"!
```
[ ] Yes
[X] No
```
=> Space is missing before <welsh_courtname> in t_message_template

src/main/java/uk/gov/hmcts/juror/api/bureau/service/ResponseStatusUpdateServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorPaperResponseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/SummonsReplyStatusUpdateServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/SummonsReplyStatusUpdateServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7821)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=613)
Digital responses are not populating reasonable adjustments correctly - only code is displayed on JUROR DETAILS and REASONABLE ADJUSTMENT REPORT. Note - paper responses is fine.
!image-20240717-095546.png|width=1245,height=747,alt="image-20240717-095546.png"!
!image-20240717-095649.png|width=1306,height=739,alt="image-20240717-095649.png"!
!image-20240717-095739.png|width=1339,height=614,alt="image-20240717-095739.png"!
```
[ ] Yes
[X] No
```
=> Digital responses - Reasonable adjustments detail only displaying code on JUROR DETAILS and REASONABLE ADJ REPORT

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/AuditControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/grouped/ExcusedAndDisqualifiedListReportITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/PoolAttendanceAuditReportITest.java, src/integration-test/resources/db/JurorRecordController_jurorDetailThirdPartyRequestBureau.sql, src/integration-test/resources/db/JurorRecordController_processNameChangeApproval.sql, src/main/java/uk/gov/hmcts/juror/api/bureau/service/ResponseStatusUpdateServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/EditJurorRecordRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/JurorThirdPartyDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorDetailsResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/Juror.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/JurorThirdParty.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/jurorresponse/DigitalResponse.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/juror/JurorThirdPartyRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorThirdPartyService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorThirdPartyServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/SummonsReplyStatusUpdateServiceImpl.java, src/main/resources/db/migrationv2/V2_24__juror_third_party_details.sql, src/test/java/uk/gov/hmcts/juror/api/juror/service/StraightThroughProcessorImplTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/SummonsReplyStatusUpdateServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8053)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=708)
When updating the third party details from the juror record the option is there but it will not save the changes even when save is selected in the application.
[~accountid:62306f3e50cceb0070797d12]  a design change is required to this section to allow the user to select how the juror should be contacted i.e contact via third party or contact via juror details.
We will need to update the edit juror details API to support the third party details section.
Add a new table for juror_third_party
Update the get juror details API to include third party details
Update the FE to send / load in this new data
Update digital and paper …
=> Third party details in the juror record does not save the details

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/UserControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/utils/SecurityUtil.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8094)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=721)
Hide "Expenses approval limits" for Court Managers and SJO's
```
[ ] Yes
[X] No
```
=> Hide "Expenses approval limits" for Court Managers and SJO's

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/PoolSummaryResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolStatisticsServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/PoolStatisticsServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8093)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=725)
Bureau unable to summon additional jurors to pools. "Something has changed since last viewed" error message is appearing.
15/8 ASB/BE held call with the Bureau - Looks like its because the total summoned count on the screen did not match to the number of juror_pools assigned to that pool It could be down to court owned records or inactive pools
```
[ ] Yes
[X] No
```
=> Bureau unable to summon additional jurors to pools. "Something has changed since last viewed" error message is appearing.

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorOverviewResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/PanelRepository.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8092)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=724)
Juror location not showing when on a trial
Change the logic to get the jurors location so that we don't depend on having an appear today, we get the last appearance on the record and the we can derive the appearance from that location.
Andy has discussed the issue with Ben
```
[ ] Yes
[X] No
```
=> Juror location not showing when on a trial

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorOverviewResponseDto.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8129)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=745)
we need to update the logic so when a juror is in status juror or panel we always show the room location, but if in status responded we only show the room location if they are checked in.
```
[ ] Yes
[X] No
```
=> Juror showing with a room location when they have not yet attended

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/grouped/PersonAttendingDetailReportITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/PersonAttendingSummaryReportITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/grouped/PersonAttendingDetailReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/PersonAttendingSummaryReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/grouped/PersonAttendingDetailReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/PersonAttendingSummaryReportTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8135)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=746)
Currently we include all jurors with a status responded panel and juror by default if they have the right next attendance date. Going forward we need to add a check box (as per the include summoned status) to include panel or juror status jurors and the default is of only responded jurors with the correct next attendance date:
!image-20240823-150358.png|width=1664,height=700,alt="image-20240823-150358.png"!
```
[ ] Yes
[X] No
```
=> The persons attending details and summery to add an option to include panel/juror status jurors

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/resources/db/jurormanagement/UpdateAttendanceDetails.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8163)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=753)
Bradford (402) reporting that they have 16 jurors checked in for the 29/08/2024 but the application is stating 40. 
!image-20240829-143433.png|width=560,height=337,alt="image-20240829-143433.png"!
Note: This would also override the Jury attendance audit number 
```
[ ] Yes
[X] No
```
=> Confirm attendance list is taking into account confirmed but returned trial attendances. This should only show the unconfirmed count.

src/integration-test/java/uk/gov/hmcts/juror/api/TestUtil.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/AuthenticationControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerITest.java, src/integration-test/resources/db/JurorRecordController_createManualJurorRecord.sql, src/main/java/uk/gov/hmcts/juror/api/config/bureau/BureauJwtPayload.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordController.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/JurorManualCreationRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolCreateServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/utils/SecurityUtil.java, src/test/java/uk/gov/hmcts/juror/api/config/BureauJwtPayloadTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-8190
Update to create a juror record by bureau user with create _juror permission
```
[ ] Yes
[x ] No
```
=> Task/JM-8191 Manually create a juror record

src/main/java/uk/gov/hmcts/juror/api/moj/exception/MojException.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-8185
Update to prevent deferral into current pool
```
[ ] Yes
[ x] No
```
=> task/JM-8185 Investigate how juror can have no active pools

src/main/resources/db/migrationv2/V2_36__util_report_updates_deferrals.sql
https://centralgovernmentcgi.atlassian.net/browse/JM-8219
Update to utilisation report to ignore attendance of deferred jurors before reporting period
```
[ ] Yes
[ x] No
```
=> hotfix/JM-8219 Update to utilisation report for deferred jurors

src/main/java/uk/gov/hmcts/juror/api/moj/xerox/LetterBase.java, src/main/resources/db/migrationv2/V2_38__update_court_location_loc_court_name.sql, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/LetterTestUtils.java
Update the English Court name displayed on court details name to be the name used for letters. (loc_court_name instead of loc_name)
https://centralgovernmentcgi.atlassian.net/browse/JM-7747
```
[ ] Yes
[ X] No
```
=> task JM-7747a switch from loc name to loc court name

src/main/resources/db/migrationv2/v2_40__write_printfiles_update.sql
JM-7885:
https://centralgovernmentcgi.atlassian.net/browse/JM-7885
Update write_printfiles db function to correct record count in file header
```
[ ] Yes
[x] No
```
=> dev/JM-7885 - Update write_printfiles db function

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/DeferralMaintenanceControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-27
User cannot add jurors from deferral maintenance to pools in the current week
```
[ ] Yes
[ x] No
```
=> task/JS-27 User cannot add jurors from deferral maintenance to pools

src/main/java/uk/gov/hmcts/juror/api/moj/repository/MessageTemplateRepositoryImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/repository/MessageTemplateRepositoryImplTest.java
https://tools.hmcts.net/jira/browse/JS-164
Court user is able to send a message to a Bureau owned juror
```
[ ] Yes
[x ] No
```
=> task/JS-164 Court user is able to send a message to a Bureau owned juror

src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/ExcusalRefusalLetterListRepositoryImpl.java
https://tools.hmcts.net/jira/browse/JS-168
Error when court user searches for excusal refused letter on pool number
```
[ ] Yes
[x ] No
```
=> task/JS-168 Error when court user searches for excusal refused letter

src/main/resources/db/migrationv2/V2_51__update_dashboard_functions.sql
https://tools.hmcts.net/jira/browse/JS-186
The following database functions that perform part of the daily refresh of Juror Dashboard statistics were collating data from part way through the first month of the refresh window rather than from the start of that month.
juror_dashboard.not_responded
juror_dashboard.response_times
juror_dashboard.thirdparty_online
juror_dashboard.welsh_online_responses
e.g. when run on the 17/12/24 with a refresh window of 6 months they are only retrieving data from 17/6/24 when they should be retrieving data from the 01/06/24.
Each instance of current_date - (no_of_months || ' month')::interval changed to
be to date_trunc('MONTH',current_date - (no_of_months || ' month')::interval)
```
[ ] Yes …
```
=> task/JS-186 Code fix for dashboard procedures

src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/JurorRecordFilterRequestQuery.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/FilterJurorRecord.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-211
Return juror email address in juror search allowing for sorting on email address
```
[ ] Yes
[x] No
```
=> JS-211 - Email address displayed in juror search results
