infrastructure/postgres.tf, infrastructure/sdp.tf
Add sdp user for juror_mod schema using terraform module - into stg, prod and ithc
```
[ ] Yes
[x] No
```
=> add db user for sdp

config/owasp/suppressions.xml, infrastructure/sdp.tf
Tables currently reported on manually are under a different schema so this needs adding to the scope of the sdp user
```
[ ] Yes
[x] No
```
=> add dashboard schema

build.gradle
Add AppInsights dependency for initial testing
```
[ ] Yes
[x] No
```
=> add Appinsights dependency

infrastructure/sdp.tf
remove ITHC from sdp user list
```
[ ] Yes
[x] No
```
=> remove ITHC from sdp user list

charts/juror-api/values.stg.template.yaml
=> reintroduce stg environment vars

charts/juror-api/Chart.yaml, charts/juror-api/values.dev.template.yaml, charts/juror-api/values.stg.template.yaml, charts/juror-api/values.yaml
=> update pnc url

src/main/java/uk/gov/hmcts/juror/api/juror/controller/response/JurorDetailDto.java
=> JDB-5542 - Refactor hearingDate format

src/main/resources/application.yml
Updated scheme to be https
```
[ ] Yes
[X] No
```
=> Updated scheme to be https

src/main/java/uk/gov/hmcts/juror/api/juror/controller/PublicEndpointController.java
=> JDB-5543 - Refactor response replyType

.github/workflows/ci.yml, Jenkinsfile_CNP, charts/juror-api/Chart.yaml, charts/juror-api/values.yaml
Updated config to use the correct scheduler subject
```
[ ] Yes
[X] No
```
=> Updated subject to match scheduler subject

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/UserControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/UserController.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/authentication/UsernameDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/UserService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/UserServiceModImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/UserControllerTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6588
Add username to response object of Create User endpoint
```
[ ] Yes
[X] No
```
=> Added username return once when a user is created

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/LetterControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/enumeration/letter/LetterType.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/letter/ReissueLetterServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6314
Update to align Postponed letter type with front end (both bureau and court letters will use this type)
```
[ ] Yes
[ x] No
```
=> Update to align the postponed letter type with front end

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/AdministrationCourtRoomControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/AdministrationCourtRoomController.java
Updated courtroom Permissions
```
[ ] Yes
[X] No
```
=> Updated courtroom Permissions

infrastructure/postgres.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
=> fix prod db

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/LetterControllerITest.java, src/integration-test/resources/db/letter/CourtLetterList_CertificateOfAttendance.sql, src/test/java/uk/gov/hmcts/juror/api/moj/service/letter/CourtLetterPrintServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6275
Updated unit and integration tests to now hit data and not include unnecessary loops.
Update sql for integration tests
```
[ ] Yes
[x] No
```
=> task/JM-6275: As a jury I need to be able to print a certificate of attendance (BE)

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/AdministrationControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorExpenseControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/MessagingControllerITest.java, src/integration-test/resources/db/JurorExpenseControllerITest_draftExpenseSetUp.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/AdministrationController.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/utils/SecurityUtil.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/AdministrationControllerTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceTest.java
Added support for court users to view financial loss limits
```
[ ] Yes
[X] No
```
=> Added ability for court users to view financial loss limits

.github/CODEOWNERS, infrastructure/postgres.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
=> feat: specify storage size and tier in prod

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/LetterControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/enumeration/letter/LetterType.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/ReissueLetterService.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/LetterBase.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/letter/ReissueLetterServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6648
Update "Deferred to" heading to be "Postponed to" in postponed bureau letters.
```
[ ] Yes
[x] No
```
=> update postponed bureau letters to use the correct "Postponed to" header

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/RequestPoolControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/CourtLocationDataDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/CourtQueriesRepositoryImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/CourtLocationControllerTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/response/CourtLocationsListDtoTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/CourtLocationServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-5841
- add Owner property to the court location data DTO
- update usages and tests
- refactor code and optimise imports
```
[ ] Yes
[x] No
```
=> - add Owner property to the court location data DTO

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/DisqualifyJurorITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorDetailsCommonResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorDetailsResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorOverviewResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorSummonsReplyResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/enumeration/DisqualifyCodeEnum.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/DisqualifyJurorControllerTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/summonsmanagement/DisqualifyJurorServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6664
Added the disqualification reason to the Juror common details so it can be rendered in FE
```
[ ] Yes
[ x] No
```
=> hotfix/JM-6664 Processing Outcome not displayed on disqualified response

build.gradle
=> Removed unused dependency

infrastructure/postgres.tf
https://centralgovernmentcgi.atlassian.net/browse/JM-6777
adds the required pg extensions into db for ora2pg to run.
```
[ ] Yes
[ ] No
```
=> add ora2pg required extensions

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/LetterControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/letter/court/PrintLetterDataResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/letter/court/CourtLetterPrintServiceImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-5964
Added attendance date to dto for FE letter requirements
```
[ ] Yes
[x] No
```
=> task/JM-6275: Add attendance date to dto

src/main/resources/db/migration/V1_46__update_dashboard_stats_tables.sql
https://centralgovernmentcgi.atlassian.net/browse/JM-6783
- create flyway script to update stats tables (in juror_dashboard schema) to fix column name typos
```
[ ] Yes
[X] No
```
=> task/JM-6783: Create V1_46__update_dashboard_stats_tables.sql

src/main/resources/db/migration/V1_47__update_utilisation_stats.sql
https://centralgovernmentcgi.atlassian.net/browse/JM-6680
- new flyway script to update the utilisation_stats table
```
[ ] Yes
[X] No
```
=> JM-6680: Create V1_47__update_utilisation_stats.sql

src/main/java/uk/gov/hmcts/juror/api/bureau/domain/StatsDeferrals.java, src/main/java/uk/gov/hmcts/juror/api/bureau/domain/StatsExcusals.java, src/main/java/uk/gov/hmcts/juror/api/bureau/domain/StatsNotResponded.java, src/main/java/uk/gov/hmcts/juror/api/bureau/domain/StatsNotRespondedTotals.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorDashboardCalculateServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/JurorDashboardCalculateServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/JurorDashboardDataServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/JurorDashboardServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JDB-5558
JDB-5558 refactor api align with script V1_46
```
[ ] Yes
[ x] No
```
=> JDB-5558 refactor api align with script V1_46

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorExpenseControllerITest.java, src/main/resources/db/migration/V1_50__update_expenses_views.sql
https://centralgovernmentcgi.atlassian.net/browse/JM-6756
Updated view to give correct unapproved expense values
```
[ ] Yes
[ x] No
```
=> Hotfix/JM-6756 Approved expenses shows as unapproved

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/letter/court/CertificateOfAttendanceLetterData.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6583
Updated Certificate of Attendance Json property order to fit requirements.
```
[ ] Yes
[x] No
```
=> hotfix/JM-6583: SQL Changes needed for certificate of attendance

src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6846
- update the apply default expenses flow to ignore ABSENT days
```
[ ] Yes
[x] No
```
=> hotfix/JM-6846 - update default expenses to ignore ABSENT days

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorDetailsCommonResponseDto.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6757
Changed police check status type from string to enum and updated the json property to snake case.
```
[X] Yes
[ ] No
```
=> Task/jm 6757 - Where PNC updates POLICE_CHECK status to ERROR_RETRY_NO_ERROR_REASON Court record shows "In progress"

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6801
Allows bureau users to add contact logs to jurors owned by a court.
```
[ ] Yes
[X] No
```
=> Bug (JM-6801) allow bureau users to add contact logs to court owned jurors

src/main/java/uk/gov/hmcts/juror/api/bureau/domain/StatsDeferrals.java
https://centralgovernmentcgi.atlassian.net/browse/JDB-5533
fix graphical resporting error deferral/excusal stats dashboard
```
[ ] Yes
[ x] No
```
=> JDB-5533a fix deferral dashboard

build.gradle, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/TrialControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/Appearance.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6946
Updated confirmJuryAttendance and return jury
```
[ ] Yes
[X] No
```
=> sat_on_jury not being set

infrastructure/postgres.tf
=> bump db size

build.gradle, src/integration-test/java/uk/gov/hmcts/juror/api/moj/domain/PoolCreateITest.java, src/main/java/uk/gov/hmcts/juror/api/bureau/controller/BureauResponsesController.java, src/main/java/uk/gov/hmcts/juror/api/bureau/controller/response/BureauYourWorkCounts.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauService.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/VotersRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorCommonResponseRepositoryMod.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/VotersServiceImpl.java, src/main/resources/db/migration/V1_55__Performance_Updates.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6981)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=198)
Added new endpoint to fetch counts of responses in todo and pending.
Optimised DB calls by removing unnecessary joints
```
[ ] Yes
[X] No
```
=> Code Optimisations for Your work pages

src/main/resources/db/migration/ V1_56__Performance_Updates2.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6980)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=200)
```
[ ] Yes
[X] No
```
=> DB Optimisations - Your work

infrastructure/postgres.tf
=> turn off enable_temp_tablespaces_on_local_ssd

src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementController.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/jurormanagement/ModifyConfirmedAttendanceDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/Appearance.java, src/main/java/uk/gov/hmcts/juror/api/moj/exception/MojException.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/poolmanagement/ManagePoolsServiceImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6729
Update to allow modification to a jurors confirmed attendance
```
[ ] Yes
[ x] No
```
=> hotfix/JM-6729 Modify a jurors confirmed attendance

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/PanelControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7012
https://centralgovernmentcgi.atlassian.net/browse/JM-7015
- fix query to retrieve all jurors
- update tests to assert counts and pools are correct
```
[ ] Yes
[X] No
```
=> hotfix/JM-7012: Fix available jurors query

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/TrialControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7014
- Add validation check when creating a trial to ensure the trial number is not already in use at the court location
- Update tests
```
[ ] Yes
[X] No
```
=> hotfix/JM-7014: Enforce unique trial numbers across the same court location

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerITest.java, src/integration-test/resources/db/JurorRecordController_createJurorOpticReference.sql, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6671
Added logic to prevent user from adding a optic ref number when the processing status is closed or processing complete flag is true
```
[ ] Yes
[X] No
```
=> Response in Awaiting information list but is complete

src/main/java/uk/gov/hmcts/juror/api/moj/controller/TrialController.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/trial/CreatePanelDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/trial/JurorListRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/trial/ReturnJuryDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/trial/PanelController.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/PanelControllerTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImplTest.java
Added support for dynamic trial and panel dates
```
[ ] Yes
[X] No
```
=> Added support for optional dynamic dates to trials and panels

src/integration-test/resources/db/trial/Panel.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/PanelRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7013
- update panel logic to use new repository methods with specific location code filters
- update unit/integration tests
```
[ ] Yes
[X] No
```
=> hotfix/JM-7013: Fix create a panel when trials share the same number across different locations

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/resources/db/JurorManagementController_poolsAtCourtLocation.sql, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
=> hotfix/JM-7028 - Random dismissal - fix to include jurors not in attendance

src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementController.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6969
Added new endpoint to mark a juror as absent. 
```
[ ] Yes
[x] No
```
=> hotfix/JM-6969: Mark as absent doesn't work from record attendance

src/main/java/uk/gov/hmcts/juror/api/moj/service/UserServiceModImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7066
Added owners to user service (tmp until we move to AD when owner will be removed from the user table)
```
[ ] Yes
[X] No
```
=> Added tmp fixes for user owner until we move to AD

src/main/java/uk/gov/hmcts/juror/api/moj/repository/MessageTemplateRepositoryImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/repository/MessageTemplateRepositoryImplTest.java
Allowed Bureau users to filter by court
```
[ ] Yes
[X] No
```
=> Added ability for bureau users to filter by court

src/main/java/uk/gov/hmcts/juror/api/juror/domain/CourtLocation.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/trial/Courtroom.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7091)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=235)
Fixed stack overflow issue
```
[ ] Yes
[X] No
```
=> Adding an assembly room to a court causes an infinite loop and breaks login when working as system administrator

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/AdministrationCourtRoomControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/AdministrationHolidaysControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/AdministrationJudgeControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/AdministrationCourtRoomController.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/AdministrationHolidaysController.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/AdministrationJudgeController.java, src/main/java/uk/gov/hmcts/juror/api/moj/utils/SecurityUtil.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7093
Updated permissions for the following api endpoints to allow for court officers:
- AdministrationCourtRoomController
- AdministrationHolidaysController
- AdministrationJudgeController
```
[ ] Yes
[x] No
```
=> Task/jm 7122 - Can't see admin as a normal officer only a manager

src/main/java/uk/gov/hmcts/juror/api/moj/report/AbstractGroupedReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/AbstractReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/AbstractStandardReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/DataType.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/IDataType.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/AbstractGroupedReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/AbstractGroupedReportTestSupport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/AbstractReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/AbstractReportTestSupport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/CurrentPoolStatusReportTest.java
Added additional utility functions to abstract reports 
```
[ ] Yes
[X] No
```
=> Added additional utility functions to abstract reports 

src/main/resources/db/migration/V1_61__removed_blank_none_from_resonable_adjustments.sql
Updated migration to update juror reasonable adjustment code before deleting the redundant code
```
[ ] Yes
[X] No
```
=> Updated migration to update juror reasonable adjustment code before deleting the redundant code

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/resources/db/jurormanagement/InitAddAttendanceDay.sql, src/integration-test/resources/db/jurormanagement/InitNonAttendance.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementController.java, src/main/java/uk/gov/hmcts/juror/api/moj/enumeration/jurormanagement/JurorStatusGroup.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7133
Fixed bug to allow adding attendance and non-attendance for completed jurors
```
[ ] Yes
[ x] No
```
=> hotfix/JM-7133  Cannot add attendances or non attendance days for jurors once completed

src/integration-test/java/uk/gov/hmcts/juror/api/bureau/controller/BureauBacklogAllocateControllerTest.java, src/integration-test/java/uk/gov/hmcts/juror/api/bureau/controller/BureauBacklogCountControllerTest.java, src/integration-test/java/uk/gov/hmcts/juror/api/bureau/controller/BureauOfficerAllocatedRepliesControllerTest.java, src/main/java/uk/gov/hmcts/juror/api/bureau/controller/BureauOfficerAllocatedRepliesController.java, src/main/java/uk/gov/hmcts/juror/api/bureau/controller/request/BureauBacklogAllocateRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/bureau/controller/response/BureauBacklogCountData.java, src/main/java/uk/gov/hmcts/juror/api/bureau/controller/response/BureauOfficerAllocatedData.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/AutoAssignmentServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauBacklogAllocateServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauBacklogCountService.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauBacklogCountServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauOfficerAllocatedRepliesServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/UrgencyServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/UserServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/juror/domain/JurorResponseQueries.java, src/main/java/uk/gov/hmcts/juror/api/juror/service/StraightThroughProcessorImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/jurorresponse/AbstractJurorResponse.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorPaperResponseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/staff/StaffServiceImpl.java, src/main/resources/db/migration/V1_62__juror_response_table_defaults.sql, src/test/java/uk/gov/hmcts/juror/api/bureau/service/AutoAssignmentServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/BureauBacklogAllocateServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/BureauBacklogCountServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/BureauOfficerAllocatedRepliesServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/juror/service/StraightThroughProcessorImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7127)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=259)
the numbers on the assign replies screen and the amount a officer actually has is different
```
[ ] Yes
[X] No
```
=> UAT - Numbers on assign reply screen and actual amount on officer to do is different

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/RequestPoolControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IPoolRequestRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/PoolRequestRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolRequestServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/poolmanagement/ManagePoolsServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/PoolRequestServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6941)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ajuror-api&pullRequest=262)
Created a new pool as a court user
Went to create a new juror to add to this pool
New pool is not shown in pools available list
```
[ ] Yes
[X] No
```
=> Court created pool not displayed when I manually create a juror

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/letter/court/PrintLetterDataResponseDto.java
Excluded nulls from print letter response to reduce network traffic
```
[ ] Yes
[X] No
```
=> Excluded nulls from print letter response to reduce network traffic

src/integration-test/java/uk/gov/hmcts/juror/api/AbstractControllerIntegrationTest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorExpenseControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/MessagingControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/bespoke/FinancialAuditReportsITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/expense/CombinedExpenseDetailsDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/expense/ExpenseDetailsWithOriginalDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/report/FinancialAuditReportServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/request/expense/CombinedExpenseDetailsDtoTest.java
Added total due/paid to financial audit response.
Added security checks to financial audit endpoint
```
[ ] Yes
[X] No
```
=> Added total due / paid to financial audit reports.

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/AuthenticationControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/config/bureau/BureauJwtPayload.java, src/test/java/uk/gov/hmcts/juror/api/config/BureauJwtPayloadTest.java
Added email to JWT
```
[ ] Yes
[X] No
```
=> Added email to JWT

src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorResponseCommonRepositoryModImpl.java
Made summons reply search case insensitive
```
[ ] Yes
[ ] No
```
=> Ignored case on search

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/JuryListReportITest.java, src/integration-test/resources/db/mod/reports/JuryListITest_typical.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/reports/request/StandardReportRequest.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/AbstractReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/grouped/PostponedListByDateReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/AbaccusReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/CurrentPoolStatusReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/DeferredListByDateReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/IncompleteServiceReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/JuryListReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/NextAttendanceDayReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/NonRespondedReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/PanelListDetailedReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/PanelSummaryReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/PostponedListByPoolReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/UndeliverableListReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/AbstractGroupedReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/AbstractReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/AbstractStandardReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/JuryListReportTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6403
Added JuryListReport and changes to AbstractReport. Added unit and integration tests.
```
[ ] Yes
[x] No
```
=> task/JM-7145: As a juror officer I want to be able to generate a jury list report (BE)

src/integration-test/java/uk/gov/hmcts/juror/api/juror/controller/PublicEndpointControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/juror/api/juror/controller/request/JurorResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/juror/service/JurorServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/juror/service/JurorServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JDB-5561
remove reference SN with reasonableAdjustments
```
[ ] Yes
[ x] No
```
=> JDB-5561 remove reference SN with reasonableAdjustments

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/ManagePoolControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/ManagePoolController.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IPoolRequestRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/PoolRequestRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/poolmanagement/ManagePoolsService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/poolmanagement/ManagePoolsServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/DeferralMaintenanceControllerTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/poolmanagement/ManagePoolsServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7152
Update to add parameter to find pools for reassignment
```
[ ] Yes
[ x] No
```
=> Hotfix/JM-7152 Filter pools for reassignment only

src/main/java/uk/gov/hmcts/juror/api/moj/repository/CoronerPoolRepositoryImpl.java
Updated Coroner search to have Requested by be case insensitive
```
[ ] Yes
[X] No
```
=> Made coroner search case-insensitive

src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/IJurorCommonResponseRepositoryMod.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/IJurorCommonResponseRepositoryModImpl.java
Fixed issue where counts could be miss aligned
```
[ ] Yes
[X] No
```
=> Fixed issue where counts could be miss aligned

src/main/resources/db/migration/V1_69__alter_content_store.sql
=> JM-7193 Alter content store table

src/main/resources/db/migration/V1_71__alter_voters_table.sql
https://centralgovernmentcgi.atlassian.net/browse/JM-7275
- alter the voters table to add a new index on loc_code
```
[ ] Yes
[X] No
```
=> JM-7275: Add loc_code index to voters table

infrastructure/postgres.tf
https://tools.hmcts.net/jira/browse/DTSPO-17654
```
[ ] Yes
[x] No
```
=> feat: added Juror DB Admin access

src/main/resources/db/migration/V1_75__create_jurorhistory_index_jurornumber_datecreated.sql
Added index to juror history 
```
[ ] Yes
[X] No
```
=> Performance fix - Juror Search

src/integration-test/java/uk/gov/hmcts/juror/api/AbstractIntegrationTest.java, src/integration-test/java/uk/gov/hmcts/juror/api/TestUtil.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/grouped/PersonAttendingDetailReportITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/PersonAttendingSummaryReportITest.java, src/integration-test/resources/db/mod/reports/PersonAttendingSummaryReportITest_typical.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/reports/request/StandardReportRequest.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/AbstractReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/grouped/PersonAttendingDetailReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/PersonAttendingSummaryReport.java, src/test/java/uk/gov/hmcts/juror/api/TestUtils.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/UserServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/LetterControllerTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/grouped/PersonAttendingDetailReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/PersonAttendingSummaryReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/DeletePoolServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/PoolCreateServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/summonsmanagement/JurorResponseRetrieveServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6369
Adds persons attending report
```
[ ] Yes
[X] No
```
=> Feat (JM-6371) add persons attending summary report

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/grouped/PersonAttendingDetailReportITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/PersonAttendingSummaryReportITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/grouped/PersonAttendingDetailReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/PersonAttendingSummaryReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/grouped/PersonAttendingDetailReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/PersonAttendingSummaryReportTest.java
N/A
Fix ordering in persons attending repots
```
[ ] Yes
[X] No
```
=> Bug (JM-6371) add ordering to persons attending reports

src/main/resources/db/migration/V1_79__update_procedure_payment_files_to_clob_write_to_clob.sql
=> hotfix/JM-7031 Payment stored procedure does not generate any data in content_store

src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/IJurorCommonResponseRepositoryModImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7311)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=343)
The “You Work” pages (todo, awaiting-info, complete) are failing PVT as page load times takes longer then 1.5 seconds 95% of the time.
!image-20240516-165215.png|width=1313,height=465,alt="image-20240516-165215.png"!
```
[ ] Yes
[X] No
```
=> Improve the performance of the "Your Work" pages

src/main/resources/db/migration/V1_84__update_procedure_payment_files_to_clob_write_to_clob.sql, src/main/resources/db/migration/V1_87__create_abaccus_view.sql
=> hotfix/task/JM-7302 Payment stored procedure generates data in incorrectly

src/main/java/uk/gov/hmcts/juror/api/juror/service/MessagesServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7343)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=352)
Create some Welsh comms in the DB (SMS and Email)
Trigger the court comms job
Check notify
!image (2).png|width=691,height=265,alt="image (2).png"!
```
[ ] Yes
[X] No
```
=> CourtComms job sends welsh comms twice

src/main/java/uk/gov/hmcts/juror/api/bureau/service/UserServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorResponseCommonRepositoryMod.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorResponseCommonRepositoryModImpl.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/UserServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7181
Updating code to allow paper and digital responses to be processed for reassignment between staff
```
[ ] Yes
[ x] No
```
=> hotfix/JM-7181 Unable to reassign response multi

src/main/java/uk/gov/hmcts/juror/api/bureau/controller/BureauStaffController.java, src/main/java/uk/gov/hmcts/juror/api/bureau/scheduler/BureauBatchScheduler.java, src/main/java/uk/gov/hmcts/juror/api/bureau/scheduler/CloseJurorResponsesScheduler.java, src/main/java/uk/gov/hmcts/juror/api/bureau/scheduler/UrgentSuperUrgentStatusScheduler.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/BureauProcessService.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsLetterServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsSentToCourtServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsWeeklyInfoServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorDashboardDataServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorDashboardSmartSurveyImportImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/ResponseStatusUpdateServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/ResponseUpdateServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/ScheduledService.java, src/main/java/uk/gov/hmcts/juror/api/juror/domain/JurorResponseQueries.java, src/main/java/uk/gov/hmcts/juror/api/juror/service/ExcusedCompletedCourtCommsServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/juror/service/MessagesServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/client/contracts/SchedulerServiceClient.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/jurorresponse/AbstractJurorResponse.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolRepository.java, src/test/java/uk/gov/hmcts/juror/api/bureau/scheduler/UrgentSuperUrgentStatusSchedulerTest.java, src/test/java/uk/gov/hmcts/juror/api/scheduler/UrgentSuperUrgentStatusSchedulerTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7346)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=372)
Returns an unexpected error. The logs appear as follows:
{code:json}[
{
"severityLevel": "Error",
"outerId": "0",
"message": "Cannot invoke \"uk.gov.hmcts.juror.api.moj.domain.JurorPool.getJurorNumber()\" because \"jurorDetails\" is null",
"type": "java.lang.NullPointerException",
"id": "0",
"rawStack": "java.lang.NullPointerException: Cannot invoke \"uk.gov.hmcts.juror.api.moj.domain.JurorPool.getJurorNumber()\" because \"jurorDetails\" is null\n\tat uk.gov.hmcts.juror.api.bureau.scheduler.UrgentSuperUrgentStatusScheduler.process(UrgentSuperUrgentStatusScheduler.java:58)\n\tat …
=> UrgentSuperUrgent job does not execute

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorDetailsCommonResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/Juror.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/jurorresponse/AbstractJurorResponse.java
Added hasSummonsResponse to common details
```
[ ] Yes
[X] No
```
=> Added hasSummonsResponse to common details

src/main/java/uk/gov/hmcts/juror/api/moj/service/letter/court/CourtLetterPrintServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7394)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=381)
As the title describes!
!image-20240523-114242.png|width=780,height=641,alt="image-20240523-114242.png"!
```
[ ] Yes
[X] No
```
=> Certificate of Attendance - attendance dates appear in random order

src/main/java/uk/gov/hmcts/juror/api/moj/service/UserServiceModImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7168)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=394)
Is this supposed to be shown?
!image-20240430-100644.png|width=1319,height=690,alt="image-20240430-100644.png"!
!image-20240430-100701.png|width=1367,height=358,alt="image-20240430-100701.png"!
```
[ ] Yes
[X] No
```
=> Last sign in not populated

src/main/resources/db/migration/V1_114__abaccus_view.sql
https://centralgovernmentcgi.atlassian.net/browse/JM-7419
- add new flyway migrate script to update the abaccus view (query the new modernised schema instead of the old/heritage schema)
```
[ ] Yes
[x] No
```
=> hotfix/JM-7419: Update abaccus view

src/main/java/uk/gov/hmcts/juror/api/moj/controller/reports/request/StandardReportRequest.java
N/A
Adds the trial attendance report to the allowed params in the standard report request
```
[ ] Yes
[X] No
```
=> Chore: add TrialAttendanceReport to the standard report request

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/AttendanceGraphReportITest.java, src/integration-test/resources/db/mod/reports/AttendanceGraphReportITest_typical.sql, src/main/java/uk/gov/hmcts/juror/api/moj/report/DataType.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/AttendanceGraphReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/AttendanceGraphReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/report/UtilisationReportServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-6489)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=391)
```
[ ] Yes
[X] No
```
=> As a jury officer I want to be able to generate an attendance graph (BE)

infrastructure/postgres.tf
revert to master
```
[ ] Yes
[ ] No
```
=> revert to master

src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7427)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=409)
When you try and edit an absence you are met with an error
!Screenshot 2024-05-29 at 11.47.08.png|width=941,height=796,alt="Screenshot 2024-05-29 at 11.47.08.png"!
```
[ ] Yes
[X] No
```
=> Cannot edit an absence day

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/grouped/PoolStatisticsReportITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/grouped/PoolStatusAndGraphReportITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/DataType.java
Fixed Master
```
[ ] Yes
[X] No
```
=> Fixed Master

src/main/java/uk/gov/hmcts/juror/api/bureau/scheduler/UrgentSuperUrgentStatusScheduler.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/UrgencyService.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/UrgencyServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/juror/domain/JurorResponseQueries.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorPaperResponseRepositoryMod.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/PanelRepositoryImpl.java, src/test/java/uk/gov/hmcts/juror/api/bureau/scheduler/UrgentSuperUrgentStatusSchedulerTest.java, src/test/java/uk/gov/hmcts/juror/api/scheduler/UrgentSuperUrgentStatusSchedulerTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7379)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=413)
Potentially one for [~accountid:62306f3e50cceb0070797d12], should this pick up digital and paper
```
[ ] Yes
[X] No
```
=> Cronbatch urgent super urgent job only picks up digital responses

src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsNotifyPayLoadServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsWeeklyInfoServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/juror/service/ExcusedCompletedCourtCommsServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/Juror.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7442)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=424)
Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "uk.gov.hmcts.juror.api.moj.domain.Juror.getWelsh()" is null
```
[ ] Yes
[X] No
```
=> NullPointerException where welsh flag is null on executing completed service comms scheduled job

src/main/resources/db/migration/V1_100__hk_delete_log.sql, src/main/resources/db/migration/V1_101__check_time_expired.sql, src/main/resources/db/migration/V1_102__housekeeping_content_store_deletion.sql, src/main/resources/db/migration/V1_103__housekeeping_coroner_deletion.sql, src/main/resources/db/migration/V1_104__housekeeping_holiday_deletion.sql, src/main/resources/db/migration/V1_105__housekeeping_juror_deletion.sql, src/main/resources/db/migration/V1_106__housekeeping_log_deletion.sql, src/main/resources/db/migration/V1_107__housekeeping_pool_deletion.sql, src/main/resources/db/migration/V1_108__housekeeping_trial_deletion.sql, src/main/resources/db/migration/V1_109__housekeeping_utilisation_stats_deletion.sql, src/main/resources/db/migration/V1_110__housekeeping_juror_digital_deletion.sql, src/main/resources/db/migration/V1_111__housekeeping_digital_process.sql, src/main/resources/db/migration/V1_112__housekeeping_process.sql, src/main/resources/db/migration/V1_96__pool_transfer_stored_procedures.sql, src/main/resources/db/migration/V1_97__setup_hk_tables.sql, src/main/resources/db/migration/V1_98__hk_insert_audit.sql, src/main/resources/db/migration/V1_99__hk_insert_log.sql
https://centralgovernmentcgi.atlassian.net/browse/JM-7304
Added all of the stored procedures from the juror-database repo into this repo and fixed some bugs with the housekeeping scripts.
```
[ ] Yes
[X] No
```
=> Task/jm 7304 - Adding stored procedures to flyway

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/DeferralRequestControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/ResponseExcusalService.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/DeferralRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/exception/MojException.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/DeferralResponseServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/DeferralResponseServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7008)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=417)
When deferring a juror for a second time there should be a screen warning the officer this will be a second deferral 
```
[ ] Yes
[X] No
```
=> When deferring a juror for a second time I should receive a warning message

src/main/resources/db/migration/V1_118__update_court_certificate_attendance_view.sql
https://centralgovernmentcgi.atlassian.net/browse/JM-7105
Can see juror without attendances in print Certificate of Attendance search but cannot print
```
[ ] Yes
[x] No
```
=> task/JM-7105: Fix Court Certificate Attendance View

src/integration-test/java/uk/gov/hmcts/juror/api/juror/controller/PublicEndpointControllerIntegrationTest.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsNotifyPayLoadServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsWeeklyInfoServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/juror/service/JurorServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolRequestService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolRequestServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/utils/DateUtils.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsNotifyPayLoadServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/juror/service/JurorServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7443)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=425)
Unable to send Informational comms for 045200204 : Unparseable date: "2024-06-06T10:00" java.text.ParseException: Unparseable date: "2024-06-06T10:00"
```
[ ] Yes
[X] No
```
=> WeeklyComms picks up jurors but throws an exception when attempting to send the comms

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/CreatePoolControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/PoolAdditionalSummonsDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/PoolCreateRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/exception/MojException.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolCreateServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/PoolCreateServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7130)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=431)
lets 2 officers summon at the same time it needs to block after the first one has summoned
```
[ ] Yes
[X] No
```
=> UAT - lets 2 officers summon for the same pool at the same time

src/main/java/uk/gov/hmcts/juror/api/moj/enumeration/DisqualifyCode.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7316)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=451)
The other document options appear to be working.
Attached video of issue.
!Screen Recording 2024-05-17 at 12.10.05.mov|width=1296,height=872,alt="Screen Recording 2024-05-17 at 12.10.05.mov"!
```
[ ] Yes
[X] No
```
=> "Requests for further information" and "Withdrawl Letters" document search throwing unhandled reception

build.gradle, src/main/resources/application.yml
https://centralgovernmentcgi.atlassian.net/browse/JM-7484
- use wildcards instead of comma separated values for multiple default directories
```
[ ] Yes
[X] No
```
=> task/JM-7484: Update flyway config

src/main/java/uk/gov/hmcts/juror/api/juror/domain/CourtLocation.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7399)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=459)
```
[ ] Yes
[X] No
```
=> If a juror is returned from a trial, then is added to a new trial as a juror. The juror is shown on both the old and new trial pages

src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsLetterServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/FilterableJurorDetailsRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/FilterableJurorDetailsResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorPoolDetailsDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/utils/JurorPoolUtils.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsRequestInformationLetterServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/request/FilterableJurorDetailsRequestDtoTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7382)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=%pullRequestNumber%)
Added active pool include type to get juror
```
[ ] Yes
[X] No
```
=> Added active pool include type to get juror

build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew, src/integration-test/java/uk/gov/hmcts/juror/api/AbstractIntegrationTest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/CompleteServiceControllerITest.java
=> Dependency updates

src/main/java/uk/gov/hmcts/juror/api/moj/domain/Appearance.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IFinancialAuditDetailsRepositoryImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7269)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=466)
On Edit expenses we are able to add more than 1 full day on the same Attendance day. If submitted this causes a new audit report to be created, however we cannot view this audit report as it goes to a technical error. 
```
[ ] Yes
[X] No
```
=> Edit expenses - Able to add more than one full day

src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/PanelRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7507)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=468)
!Screen Recording 2024-06-07 at 13.41.50.mov|width=3160,height=1702,alt="Screen Recording 2024-06-07 at 13.41.50.mov"!
```
[ ] Yes
[X] No
```
=> Cannot confirm attendance for Juror who has attendances on previous trials

src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/AttendanceGraphReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/AttendanceGraphReportTest.java
Fixed flaky fixed test
```
[ ] Yes
[X] No
```
=> Fixed flaky fixed test

src/main/java/uk/gov/hmcts/juror/api/moj/repository/UserRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/UserServiceModImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7522)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=473)
```
[ ] Yes
[X] No
```
=> When logging in email should be case-insensitive 

build.gradle, src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsNotifyPayLoadServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/juror/domain/CourtLocation.java, src/main/java/uk/gov/hmcts/juror/api/juror/domain/WelshCourtLocation.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/ICourtLocation.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/NotifyTemplateFieldMod.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/NotifyTemplateMapperMod.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/NotifyTemplateFieldRepositoryMod.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorCommonResponseRepositoryMod.java, src/main/resources/db/migration/V1_133__notify_template_field_updates.sql, src/test/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsNotifyPayLoadServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsRequestInformationLetterServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/bureau/service/JurorCommsSentToCourtServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7472)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=478)
Many of the fields reference old fields and classes and some letters therefore do not work at all
```
[ ] Yes
[X] No
```
=> notify_template_field for Letter Comms Job is not aligned to new data structure

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/grouped/CompletionOfServiceReportITest.java, src/integration-test/resources/db/mod/reports/CompletionOfServiceReportITest_typical.sql, src/main/java/uk/gov/hmcts/juror/api/moj/report/DataType.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/grouped/CompletionOfServiceReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/grouped/CompletionOfServiceReportTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7515)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=474)
Completed service of jurors individually and also in bulk via pool, when searching on the report for the dates of completion I selected there are no results returned at all times.
```
[ ] Yes
[X] No
```
=> Completion of Service report - doesn't return any results

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/DeferralMaintenanceControllerITest.java, src/integration-test/resources/db/DeferralMaintenanceProcessJurorTest.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IReissueLetterRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IReissueLetterRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PrintDataService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PrintDataServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6703
Unable to delete the letter from the printing queue, logs report non unique record
```
[ ] Yes
[ X] No
```
=> task/JM-6703 Unable to delete the letter from the printing queue, logs report non unique record

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/TrialControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7262
Updated return jury (TrialService) to update attendance type when confirming attendance for returning a jury member
```
[ ] Yes
[x] No
```
=> Attendance details on unpaid attendance incorrect after returning jury

src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorDashboardSmartSurveyImportImpl.java
Fixed styles
```
[ ] Yes
[X] No
```
=> Fixed styles

src/main/resources/db/migration/V1_137__update_court_letter_procedures_views.sql
https://centralgovernmentcgi.atlassian.net/browse/JM-7505
Removed a sanity check to ensure the record was court only
```
[ ] Yes
[X] No
```
=> JM-7505 - Certificate of Attendance - juror doesn't appear if they have >1 day attendance

src/main/resources/db/migration/V1_132__print_files_to_clob_update.sql
This is a duplication of https://github.com/hmcts/juror-api/pull/476 due to fork branches not running the jenkins pipeline properly
```
[ ] Yes
[x] No
```
=> Hotfix/printjob fix - 

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorOverviewResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/AppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/PanelRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7532)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=487)
```
[ ] Yes
[X] No
```
=> Add additional attendance info to API response

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/ManagePoolControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/PoolSummaryResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolStatisticsServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/PoolStatisticsServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7563
Added pool type property to pool summary Dto
```
[ ] Yes
[ x] No
```
=> hotfix/JM-7563 Pool type incorrect in pool summary

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7600)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=511)
!image-20240620-082823.png|width=1812,height=797,alt="image-20240620-082823.png"!
this should error at you and say ‘can not empanel more jurors than selected’
```
[ ] Yes
[X] No
```
=> Remove the error that stops future dates for non-attendance days

src/main/java/uk/gov/hmcts/juror/api/moj/service/poolmanagement/JurorManagementServiceImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7597
update to make owner of new pool correct value
```
[ ] Yes
[ x] No
```
=> hotfix/JM-7597 Errors when I try to reassign a juror to a satellite and create a new pool 

src/main/java/uk/gov/hmcts/juror/api/moj/utils/PaginationUtil.java, src/test/java/uk/gov/hmcts/juror/api/moj/utils/PaginationUtilTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7615)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=517)
!image-20240620-141256.png|width=2212,height=632,alt="image-20240620-141256.png"!
```
[ ] Yes
[X] No
```
=> Export contact details - if results set >500, returns "no matching results"

infrastructure/test.tfvars
=> introduce test.tfvars

infrastructure/test.tfvars
=> correct pgsql_storage_mb

src/main/resources/db/migration/V1_145__juror_history_update_ref_length.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7621)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=531)
!image-20240621-074458.png|width=1499,height=478,alt="image-20240621-074458.png"!
!image-20240621-074611.png|width=1370,height=252,alt="image-20240621-074611.png"!
!image-20240621-074801.png|width=559,height=35,alt="image-20240621-074801.png"!
```
[ ] Yes
[X] No
```
=> Technical error if trial number is >10 chars

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorOverviewResponseDto.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7637)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=527)
Change link not working
!image-20240621-144346.png|width=1692,height=667,alt="image-20240621-144346.png"!
```
[ ] Yes
[X] No
```
=> Overview section on the overview page for court user not showing correctly

src/main/java/uk/gov/hmcts/juror/api/moj/repository/IReissueLetterRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IReissueLetterRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/ReissueLetterServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/letter/ReissueLetterServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-6703
added clause to check to see if the print file record has not been extracted
```
[ ] Yes
[ x] No
```
=> Unable to delete the letter from the printing queue, logs report non unique record

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/grouped/PaymentStatusReportITest.java, src/integration-test/resources/db/mod/reports/PaymentStatusReportITest_typical.sql, src/main/java/uk/gov/hmcts/juror/api/moj/domain/PaymentData.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/datatypes/PaymentStatusDataTypes.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceImpl.java, src/main/resources/db/migration/V1_147__payment_job_update.sql, src/test/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7646)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=534)
```
[ ] Yes
[X] No
```
=> Payment Job adds entries with 0 value

src/main/resources/db/migration/V1_149__history_update.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7651)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=537)
!Screenshot 2024-06-25 at 18.10.52.png|width=753,height=378,alt="Screenshot 2024-06-25 at 18.10.52.png"!
```
[ ] Yes
[X] No
```
=> Juror History -  Jury confirmed attendance wording incorrect

src/main/resources/db/migration/V1_154__performance_job_updates.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7668)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=542)
juror_dashboard.response_times Stored Procedure
Error is
response_times failed - error:->function abs(interval) does not exist||No function matches the given name and argument types. You might need to add explicit type casts.
```
[ ] Yes
[X] No
```
=> Performance Stats not Producing and response Stats data

src/main/java/uk/gov/hmcts/juror/api/juror/service/PublicAuthenticationServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorServiceMod.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorServiceModImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/summonsmanagement/JurorResponseService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/summonsmanagement/JurorResponseServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7659)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=546)
An error is thrown when entering juror response via front end(DEMO). Error message is “There is a problem“. Used the following info: Juror number: 200188632, Last Name: Mogannam, Postcode: BB3 5TQ
Error from logs:
{"timestamp":1719404926084,"status":500,"error":"Internal Server Error","exception":"org.springframework.dao.IncorrectResultSizeDataAccessException","message":"jakarta.persistence.NonUniqueResultException: Query did not return a unique result: 2 results were returned","path":"/api/v1/auth/juror"}
org.hibernate.NonUniqueResultException: Query did not return a unique result: 2 results were returned
at …
=> An error is thrown when trying to enter Juror details via front end

src/main/resources/db/migration/V1_156_print_job_file_split.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7676)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=550)
As discovered during Ben’s load testing of the PRINT_JOB
```
[ ] Yes
[X] No
```
=> PRINT files are not consolidated into separate files of 2000 rows

src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolCreateServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/LetterBase.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/letters/SummonsLetter.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7636
Fix issue where english summons letter is being sent out for users summoned to a welsh court.
```
[ ] Yes
[x] No
```
=> hotfix - English summons (5221) generated for 457 (Swansea) summoned jurors

src/test/java/uk/gov/hmcts/juror/api/testsupport/PostgresqlContainer.java
change to ACR postgres image
```
[ ] Yes
[x] No
```
=> change to ACR postgres image

src/test/java/uk/gov/hmcts/juror/api/testsupport/PostgresqlContainer.java
try sds ACR
```
[ ] Yes
[ ] No
```
=> try sds ACR

src/main/java/uk/gov/hmcts/juror/api/moj/domain/SummonsSnapshot.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/LetterBase.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/ConfirmLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/DeferralDeniedLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/DeferralLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/ExcusalDeniedLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/ExcusalLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/LetterBaseTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/LetterTestUtils.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/PostponeLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/RequestInfoLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/SummonsLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/SummonsReminderLetterTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/xerox/WithdrawalLetterTest.java
Added THE CROWN COURT AT prefix to letters
```
[ ] Yes
[X] No
```
=> Added THE CROWN COURT AT prefix to letters

src/main/java/uk/gov/hmcts/juror/api/moj/domain/Address.java
N/A
- ignore stringified address from the json response for court-details
```
[ ] Yes
[x] No
```
=> add @JsonIgnore to stringified address

src/main/java/uk/gov/hmcts/juror/api/moj/repository/AppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7721)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=571)
!image-20240704-140631.png|width=1298,height=536,alt="image-20240704-140631.png"!
```
[ ] Yes
[X] No
```
=> When marking a juror as Failed to attend it errors when there is an absence

src/main/java/uk/gov/hmcts/juror/api/moj/repository/AppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7803)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=597)
example of a juror this as happened for 443521003
```
[ ] Yes
[X] No
```
=> a Juror that has served for more than 10 days not getting the increased expense rates

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/grouped/PersonAttendingDetailReportITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/PersonAttendingSummaryReportITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/grouped/PersonAttendingDetailReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/PersonAttendingSummaryReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/grouped/PersonAttendingDetailReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/PersonAttendingSummaryReportTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7831)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=603)
```
[ ] Yes
[X] No
```
=> Persons attending details and summary report need to be sorted by surname

src/main/resources/db/migrationv2/V2_5__update_payment_files_to_clob_length_fix.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7814)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=600)
```
[ ] Yes
[X] No
```
=> Payment File procedure is using 9 digits instead of 7 digits for uniqueid

src/test/java/uk/gov/hmcts/juror/api/testsupport/PostgresqlContainer.java
Pg image2
```
[ ] Yes
[ ] No
```
=> update testcontainer image location

src/main/java/uk/gov/hmcts/juror/api/moj/domain/Address.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/messages/MessageSearch.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IReissueLetterRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorRepositoryImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/domain/messages/MessageSearchTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/repository/IReissueLetterRepositoryImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7856)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=615)
```
[ ] Yes
[X] No
```
=> Updated postcode search to be case insensitive 

src/main/resources/db/migrationv2/V2_7__update_bank_name_to_upper.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7845)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=609)
```
[ ] Yes
[X] No
```
=> Bank account name on payment file should be uppercase

src/main/java/uk/gov/hmcts/juror/api/moj/controller/ManagePoolController.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/PoolStatisticsWithPoolJoin.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/PoolStatisticsRepositoryImpl.java, src/main/resources/db/migrationv2/V2_8__updated_pool_stats_performance.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7760)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=616)
this appears to be a performance related issue
```
[ ] Yes
[X] No
```
=> Summoning progress timing out when trying to search for any court

src/integration-test/java/uk/gov/hmcts/juror/api/AbstractIntegrationTest.java, src/integration-test/resources/db/letter/CourtLetterList_CertificateOfAttendance.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/LetterController.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/letter/court/CertificateOfAttendanceLetterList.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/CertificateOfAttendanceListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/DeferralDeniedLetterListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/DeferralGrantedLetterListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/ExcusalGrantedLetterListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/ExcusalRefusalLetterListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/FailedToAttendLetterListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/ICertificateOfAttendanceListRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/PostponementLetterListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/ShowCauseLetterListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/WithdrawalLetterListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/letter/court/CourtLetterPrintServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/letter/court/CourtLetterServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/utils/DataUtils.java, src/main/resources/db/migrationv2/V2_10__certificate_of_attendance_performance.sql, src/test/java/uk/gov/hmcts/juror/api/moj/service/letter/CourtLetterPrintServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/letter/CourtLetterServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7853)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=619)
Also, I have a lot of jurors needing Certificate of Attendance for work or they are losing money, as we cant approve expenses. The COAs are still showing up with none of the dates on them even though on their profile it says 6 attendance days Certificate of attendance not showing all the days juror attended. Can this be resolved please.
+*Actions taken:*+
* Fixed issue where welsh courts would fail to generate court letters (if welsh language flag was not set)
* Full redesign of how we query the database occurred to improve performance
* Added new database index’s to improve search performance
**Does this PR introduce a breaking …
=> Certificate of Attendance for work

src/main/java/uk/gov/hmcts/juror/api/moj/service/DeferralResponseServiceImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7863
Update to set the juror pool owner to latest value of pool and also set the next date to return date of pool
```
[ ] Yes
[x ] No
```
=> hotfix/JM-7863 Refusing deferral puts juror in no mans land

src/main/java/uk/gov/hmcts/juror/api/moj/domain/Juror.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/utils/DataUtils.java, src/main/resources/db/migrationv2/V2_11__payment_job_update.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7877)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=625)
```
[ ] Yes
[X] No
```
=> Expense File can have a space prefix on juror name this is incorrect

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorDetailsCommonResponseDto.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7894)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=631)
```
[ ] Yes
[X] No
```
=> When viewing the juror details page. I should see the attendances for the court I am logged in as not the active court the juror is at

src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7895)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=635)
Expenses showing a "£0" Balance - Payment capped at £64.95 after 10 days. Unable to authorise payments
```
[ ] Yes
[X] No
```
=> Expenses long day flag not updated when a attendance is added in the past (future attendances should get updated)

infrastructure/postgres.tf, infrastructure/test.tfvars, infrastructure/variables.tf
force pwd reset in test
```
[ ] Yes
[x] No
```
=> force pwd reset in test

infrastructure/test.tfvars
unset date on password resetto align with master
```
[ ] Yes
[x] No
```
=> unset date on password resetto align with master

src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/poolmanagement/JurorManagementServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceTest.java
=> Approval fix

src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/JurorAppearanceDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/jurormanagement/RetrieveAttendanceDetailsDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/jurormanagement/UpdateAttendanceDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/IJurorStatus.java, src/main/java/uk/gov/hmcts/juror/api/moj/enumeration/jurormanagement/JurorStatusGroup.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7929)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=649)
```
[ ] Yes
[X] No
```
=> Code fix required to update day confirmation to include all check-in / checked-out jurors that do not have the status of JUROR 

Jenkinsfile_CNP
set env var for flyway
```
[ ] Yes
[x] No
```
=> set env var for flyway

Jenkinsfile_CNP
Move setting env var to before prod migration
```
[ ] Yes
[x] No
```
=> Move setting env var to before prod migration

src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordController.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/Juror.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/MessageTemplateRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/MessagingServiceImpl.java, src/main/resources/db/migrationv2/V2_14__added_combined_phone_number.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7912)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=658)
the messaging seems to be pulling through the wrong phone number for messaging jurors
```
[ ] Yes
[X] No
```
=> Messaging pulling through the wrong phone number for the juror

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/BallotPanelPoolReportITest.java, src/integration-test/resources/db/mod/reports/BallotPanelPoolReportITest.sql, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/BallotPanelPoolReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/BallotPanelPoolReportTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7909)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=653)
```
[ ] Yes
[X] No
```
=> Ballot cards from the pool include all jurors not just responded jurors

charts/juror-api/Chart.yaml
bump chart
```
[ ] Yes
[x] No
```
=> bump chart

charts/juror-api/Chart.yaml, charts/juror-api/values.demo.template.yaml, charts/juror-api/values.ithc.template.yaml
revert changes and bump chart again
```
[ ] Yes
[x] No
```
=> revert changes and bump chart again

src/main/java/uk/gov/hmcts/juror/api/moj/service/ExcusalResponseServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7957)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=671)
```
[ ] Yes
[X] No
```
=> Court can not excuse a juror unless they have a response

src/main/java/uk/gov/hmcts/juror/api/moj/repository/PoolRequestRepositoryImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7955)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=670)
```
[ ] Yes
[X] No
```
=> When deleting a pool, pool comments should also be deleted

build.gradle
allow override on cleanDisabled
Note - this has no effect on the functionality and so only needs to be verified by a developer
```
[ ] Yes
[x] No
```
=> allow override on cleanDisabled

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/LetterControllerITest.java, src/integration-test/resources/db/letter/CourtLetterList_DeferralDenied.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorPaperResponseDetailDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/letter/court/LetterListBase.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/DeferralDeniedLetterListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorPaperResponseServiceImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-7983
https://centralgovernmentcgi.atlassian.net/browse/JM-7952
https://centralgovernmentcgi.atlassian.net/browse/JM-7989
=> Stabilisation9

src/main/java/uk/gov/hmcts/juror/api/moj/service/poolmanagement/JurorManagementServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorManagementServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-7947)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=683)
When the user attempts to transfer a Juror(342906582) to a different court, they press confirm and are then presented with a 'Technical error' message.
An error message "Sorry, there is a technical problem" was seen by the user on 25th July between 09:25 and 09:30. However, I could not find any reference to juror 342906582 and the user's ID in the logs. 
+*Other issues fixed:*+
Fixed an issue where if you transfered a juror from court A to court B but then court B transfered the juror back to Court A the application would fail
```
[ ] Yes
[X] No
```
=> INC2531610 - Technical error when transferring juror to another court

src/integration-test/resources/db/letter/CourtLetterList_FailedToAttend.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/FailedToAttendLetterListRepositoryImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-8015
Updated failed to attend court letter to use QueryDsl instead of view for performance
```
[ ] Yes
[ x] No
```
=> task/JM-8015 Failed to attend letter

src/integration-test/resources/db/letter/CourtLetterList_Withdrawal.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/WithdrawalLetterListRepositoryImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-8016
Court withdrawal letters updated to use querydsl rather than view
```
[ ] Yes
[ x] No
```
=> task/JM-8016 Court Withdrawal letter

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/LetterControllerITest.java, src/integration-test/resources/db/letter/CourtLetterList_ExcusalGranted.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/ExcusalGrantedLetterListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/IExcusalGrantedLetterListRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/letter/court/CourtLetterServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/letter/CourtLetterServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-8004
Court Excusal Granted letter updated to use queryDsl rather than view
```
[ ] Yes
[ x] No
```
=> JM-8004 ExcusalGrantedLetter

src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/ExcusalRefusalLetterListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/ExcusalResponseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/letter/court/CourtExcusalRefusedLetterServiceImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-8014
Updated court excusal refusal letter to use querydsl rather than view
```
[ ] Yes
[ x] No
```
=> task/JM-8014 Court Excusal refusal letter

src/main/java/uk/gov/hmcts/juror/api/moj/service/AppearanceCreationServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8030)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=695)
```
[ ] Yes
[X] No
```
=> Confirming a trial gives a technical error (After Stabilisation 10 deployment)

src/main/java/uk/gov/hmcts/juror/api/moj/enumeration/AppearanceStage.java, src/main/java/uk/gov/hmcts/juror/api/moj/exception/MojException.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8034)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=698)
```
[ ] Yes
[X] No
```
=> Confirming a trial attendance can override an existing confirmed attendance

src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8059)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=706)
```
[ ] Yes
[X] No
```
=> Unable to confirm jury attendance for a day that has a deleted appearance

src/main/resources/db/migrationv2/V2_25_require_pnc_batch_strip_double_space.sql
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8079)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=711)
!image-20240816-104222.png|width=182,height=343,alt="image-20240816-104222.png"!
```
[ ] Yes
[X] No
```
=> PNC Batch Job fails when a post code contains a double space

build.gradle, src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorDashboardSmartSurveyImportImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/ITrialRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/PoolRequestServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8075)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=709)
+*Other fixes applied:*+
* Removed any jurors that have  a confirmed jury attendances from the day but are not in JUROR status from the jurors in waiting list 
* Updated juror on a trial list to show historical confirmed attendances (Even if the trial has ended)
```
[ ] Yes
[X] No
```
=> Can not return Jurors that are in any status other then PANEL and JUROR

src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorRepositoryImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8089)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=718)
```
[ ] Yes
[X] No
```
=> Updated juror name search to ignore case ensuring index's get hit

src/main/java/uk/gov/hmcts/juror/api/juror/service/JurorPersistenceServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8087)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=716)
```
[ ] Yes
[X] No
```
=> Updating StraightThroughProcessing logging so these don't show up as Exceptions on the Azure dashboards 

src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/FinancialAuditServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/RevisionService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/RevisionServiceImpl.java, src/main/resources/db/migrationv2/V2_27__juror_audit_index.sql, src/test/java/uk/gov/hmcts/juror/api/moj/service/FinancialAuditServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/RevisionServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8090)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=719)
```
[ ] Yes
[X] No
```
=> Improve performance of getting latest juror revision

src/main/java/uk/gov/hmcts/juror/api/moj/repository/jurorresponse/JurorResponseCommonRepositoryModImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8099)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=722)
```
[ ] Yes
[X] No
```
=> Advanced juror search as a bureau team leader where I am searching for assigned responses should exclude court owned records 

src/main/java/uk/gov/hmcts/juror/api/moj/service/SummonsReplyStatusUpdateServiceImpl.java
Fixed issue where digital response would only merge reason and relationship
=> Fixed issue where digital response would only merge reason and relationship

src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8105)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=727)
```
[ ] Yes
[X] No
```
=> Setting a user to on-call when they have been transferred from another court fails

src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/BallotPanelPoolReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/BallotPanelTrialReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/BallotPanelPoolReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/BallotPanelTrialReportTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8112)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=730)
```
[ ] Yes
[X] No
```
=> Order Ballot reports by last name

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/bespoke/UtilisationReportsITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/report/UtilisationReportServiceImpl.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8109)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=731)
See attached screen recording
!image-20240821-133120.png|width=1482,height=393,alt="image-20240821-133120.png"!
```
[ ] Yes
[X] No
```
=> Daily Utilisation fails if there is no data for a selected day

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordController.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8137)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=748)
```
[ ] Yes
[X] No
```
=> Permission change to allow the Bureau general users to edit change name / fix error in name option

src/main/java/uk/gov/hmcts/juror/api/moj/repository/ActivePoolsRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/PoolRequestRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/utils/PaginationUtil.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8139)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=750)
!image-20240827-140714.png|width=1560,height=492,alt="image-20240827-140714.png"!
!image-20240827-140727.png|width=1197,height=225,alt="image-20240827-140727.png"!
comment from Ben: this is because we changed how this gets derived, we will need to remove the limit from the return data for this row so setting it to -1 instead of MAX_ITEMS
```
[ ] Yes
[X] No
```
=> Active Pools Not Displaying Records

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/TrialControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/JM-8148)
>[Sonar](https://sonarcloud.io/summary/new_code?id=uk.gov.hmcts.juror%3Ahmcts&pullRequest=752)
```
[ ] Yes
[X] No
```
=> History stating jury attendance confirmed when return but do not confirm was selected

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/ElectronicPoliceCheckReportITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/DataType.java
[JM-8116](https://centralgovernmentcgi.atlassian.net/browse/JM-8116)
Updated electronic police check 'checks timed out' report header
```
[ ] Yes
[x] No
```
=> hotfix/JM-8116: Updated electronic police check 'checks timed out' report header

src/main/java/uk/gov/hmcts/juror/api/bureau/controller/response/BureauJurorDetailDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorPaperResponseServiceImpl.java
https://centralgovernmentcgi.atlassian.net/browse/JM-8188
Update to gracefully handle scenario where the staff assigned is not in the users table (this happens for migrated users)
```
[ ] Yes
[ x] No
```
=> Task/JM-8188 Pre-mod userids preventing access to digital response records

src/main/resources/db/migrationv2/V2_34__amend_require_pnc_check_view.sql
T
(https://centralgovernmentcgi.atlassian.net/browse/JM-8196)
JM-8196 remove erroneous spaces in file upload
```
[ ] Yes
[x ] No
```
=> JM-8196 Amend PNC View remove spaces last_name

build.gradle, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/DeferralReasonRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-8187
Added validation to stop jurors being marked as deferred into a pool without DOB
```
[ ] Yes
[x ] No
```
=> task/JM-8187 shouldn't be able to mark a juror as deferred w/o DOB

src/main/java/uk/gov/hmcts/juror/api/juror/service/PublicAuthenticationServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/Juror.java, src/main/resources/db/migrationv2/V2_45__alter_juror_add_lock_time.sql
Juror public user authentication lock out
https://centralgovernmentcgi.atlassian.net/browse/JM-8230
```
[ ] Yes
[x ] No
```
=> JM-8230 juror public user lock out

src/main/java/uk/gov/hmcts/juror/api/moj/service/letter/court/CourtLetterPrintServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/xerox/XeroxConstants.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/juror/api/moj/service/letter/CourtLetterPrintServiceTest.java
Amend Welsh month translation
https://centralgovernmentcgi.atlassian.net/browse/JM-8232
```
[ ] Yes
[x ] No
```
=> JM-8232 amend Welsh month translation

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/resources/db/jurormanagement/InitAppearanceTests.sql, src/integration-test/resources/db/jurormanagement/RetrieveAttendanceDetails.sql, src/integration-test/resources/db/jurormanagement/UnconfirmedJurors.sql, src/integration-test/resources/db/jurormanagement/UpdateAttendanceDetails.sql, src/main/java/uk/gov/hmcts/juror/api/moj/enumeration/jurormanagement/JurorStatusGroup.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-8227
As a jury officer I want to be able to confirm juror attendance for the day
```
[ ] Yes
[ x] No
```
=> Feature/JM-8227 As a jury officer I want to be able to confirm juror attendance for the day

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/resources/db/jurormanagement/ConfirmJuryAttendancePartiallyConfirmed.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/jurormanagement/UpdateAttendanceDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/trial/PanelController.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/AppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImplTest.java
https://centralgovernmentcgi.atlassian.net/browse/JM-8201
Update to allow multiple juror attendance on same attendance audit number. will need FE updates as well.
```
[ ] Yes
[ x] No
```
=> task/JM-8201 Update to allow multiple juror attendance on same attendance audit number

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementController.java, src/test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerTest.java
https://tools.hmcts.net/jira/browse/JS-94
Update GET endpoints with body to support Axios requests. Will need corresponding FE changes to be updated.
```
[ ] Yes
[x ] No
```
=> task/JS-94 Update GET endpoints with body to support Axios requests

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/resources/db/jurormanagement/RetrieveAttendanceDetails.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementController.java, src/main/java/uk/gov/hmcts/juror/api/moj/exception/MojException.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/IPanelRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/PanelRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
https://tools.hmcts.net/jira/projects/JS/issues/JS-89
Update for confirming attendances
```
[ ] Yes
[x ] No
```
=> task/JS-89 Update for confirming attendances

src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java
https://tools.hmcts.net/jira/browse/JS-89
update to way confirm attendance works - scenario where juror is empanelled twice in one day
```
[ ] Yes
[x ] No
```
=> task/JS-89 Update to confirm attendance logic

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/resources/db/jurormanagement/RetrieveAttendanceDetails.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java
https://tools.hmcts.net/jira/browse/JS-89
Update for handling Panelled jurors as agreed with the business
```
[ ] Yes
[x ] No
```
=> task/JS-89 Update for handling Panelled jurors

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordControllerITest.java, src/integration-test/resources/db/JurorRecordController_updateAttendance.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/UpdateAttendanceRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceTest.java
https://tools.hmcts.net/jira/browse/JS-121
Update api to allow multiple jurors to be updated to on call at the same time
```
[ ] Yes
[ x] No
```
=> task/JS-121 Put multiple jurors on call at the same time

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/ExcusalResponseControllerITest.java, src/integration-test/resources/db/ExcusalResponse_initPaperResponse.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/trial/ITrialRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/ExcusalResponseServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-125
As a Bureau officer I don't want to move jurors to responded when there is no DOB
```
[ ] Yes
[ x] No
```
=> task/JS-125 Don't move jurors to responded when there is no DOB

src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/PanelServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-139
Empanelled juror can show in juror in waiting
```
[ ] Yes
[ x] No
```
=> task/JS-139 Empanelled juror can show in juror in waiting

src/main/java/uk/gov/hmcts/juror/api/moj/service/trial/TrialServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-123
update to current date appearance logic for reassign panel members
```
[ ] Yes
[x ] No
```
=> task/JS-123 Reassign Panel members

src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/grouped/DeferredListByCourtReportITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/report/standard/DeferredListByDateReportITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/reports/request/StandardReportRequest.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/AbstractReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/grouped/DeferredListByCourtReport.java, src/main/java/uk/gov/hmcts/juror/api/moj/report/standard/DeferredListByDateReport.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/grouped/DeferredListByCourtReportTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/report/standard/DeferredListByDateReportTest.java
https://tools.hmcts.net/jira/browse/JS-122
As a Bureau/Court officer I want to be able to filter on the deferral list report
```
[ ] Yes
[ x] No
```
=> task/JS-122  I want to be able to filter on the deferral list report

src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-170
Fix for issue where Jury attendance audit number is incorrect
```
[ ] Yes
[x ] No
```
=> task/JS-170 Jury attendance audit number is incorrect

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorManagementControllerITest.java, src/integration-test/resources/db/jurormanagement/UpdateAttendanceDetailsCheckInAll.sql, src/main/java/uk/gov/hmcts/juror/api/moj/exception/MojException.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-167
Confirmed attendances go missing
```
[ ] Yes
[x ] No
```
=> Task/JS-158 Confirmed attendances go missing

src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolRequestServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
https://tools.hmcts.net/jira/browse/JS-150
As a jury officer I want to pay jurors the higher rate after 2 weeks of service
```
[ ] Yes
[ x] No
```
=> task/JS-150 Pay jurors the higher rate after 2 weeks of service

src/main/resources/db/migrationv2/V2_47__update_delete_printfiles..sql
https://tools.hmcts.net/jira/browse/JS-130
As a Bureau officer I want to stop letters from being sent if the juror is not in the correct status
```
[ ] Yes
[x ] No
```
=> Task/JS-130 Stop letters from being sent if the juror is not in the correct status

src/main/java/uk/gov/hmcts/juror/api/moj/controller/CompleteServiceController.java
https://tools.hmcts.net/jira/browse/JS-146
update max uncomplete param
```
[ ] Yes
[x ] No
```
=> JS-146 update max uncomplete param

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/MessagingControllerITest.java, src/integration-test/resources/db/MessagingControllerITest_postSearchSetup.sql, src/main/java/uk/gov/hmcts/juror/api/moj/domain/messages/MessageSearch.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/MessageQueries.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/MessageTemplateRepositoryImpl.java
https://tools.hmcts.net/jira/browse/JS-126
As a Jury officer I want to be able to send a sentence date message for jurors that were on a trial
```
[ ] Yes
[x ] No
```
=> Task/JS-126 Send a sentence date message for jurors that were on a trial

src/main/java/uk/gov/hmcts/juror/api/moj/exception/MojException.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorPoolServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java
https://tools.hmcts.net/jira/browse/JS-188
As a user I want to see a message when there is an error on approve expense screen
```
[ ] Yes
[x ] No
```
=> Task/JS-188  message when there is an error on approve expense screen

src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorDashboardSmartSurveyImportImpl.java, src/main/java/uk/gov/hmcts/juror/api/juror/service/MessagesServiceImpl.java
JS-59
Updates to logging for dynatrace mining
```
[ ] Yes
[ x] No
```
=> task/JS-59 updates to logging for Dyntrace mining

src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-179
Create juror history event
```
[ ] Yes
[x ] No
```
=> JS-179 update juror history event

src/main/java/uk/gov/hmcts/juror/api/bureau/service/DashboardDeferralExcusalServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorDetailsResponseDto.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceTest.java
https://tools.hmcts.net/jira/browse/JS-51
extra mobile phone validation , when sending sms to juror's
```
[ ] Yes
[ x] No
```
=> JS-51 extra validation for mobile numbers in messages

build.gradle, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/LetterControllerITest.java, src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/MessagingControllerITest.java, src/integration-test/resources/db/MessagingControllerITest_postSearchSetup.sql, src/main/java/uk/gov/hmcts/juror/api/bureau/service/DashboardDeferralExcusalServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/bureau/service/JurorDashboardSmartSurveyImportImpl.java, src/main/java/uk/gov/hmcts/juror/api/juror/service/MessagesServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/CompleteServiceController.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorDetailsResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/HistoryCode.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/messages/MessageSearch.java, src/main/java/uk/gov/hmcts/juror/api/moj/exception/MojException.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/MessageQueries.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/MessageTemplateRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/letter/court/ExcusalRefusalLetterListRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorHistoryServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorPoolServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolHistoryService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolHistoryServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/ReissueLetterServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java, src/main/resources/db/migrationv2/V2_49__update_court_location_address.sql, src/main/resources/db/migrationv2/V2_51__update_dashboard_functions.sql, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorHistoryServiceImplTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceTest.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/letter/ReissueLetterServiceTest.java
JS-126
JS-159
JS-168
JS-188
JS-146
JS-51
Juror api release5.2
```
[ ] Yes
[ x] No
```
=> Release5.2

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/JurorExpenseControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/enumeration/FoodDrinkClaimType.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceTest.java
https://tools.hmcts.net/jira/browse/JS-268
Enhance Subsistence Calculation - Auto Calculate Court & Travel Time
```
[x ] Yes
[ ] No
```
=> task/JS-268 Auto Calculate Court & Travel Time

src/main/java/uk/gov/hmcts/juror/api/moj/service/SummonsReplyStatusUpdateServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-258
Default to 3rd party from a juror response
```
[ ] Yes
[ x] No
```
=> JS-258 Default to 3rd Party

src/main/java/uk/gov/hmcts/juror/api/moj/service/UndeliverableResponseServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/UndeliverableResponseServiceTest.java
https://tools.hmcts.net/jira/browse/JS-182
JM-182 synch juror status and responses
```
[ ] Yes
[ x] No
```
=> JM-182 synch juror status and responses

build.gradle, src/main/resources/db/migrationv2/V2_58__create_juror_er_schema.sql, src/test/java/uk/gov/hmcts/juror/api/testsupport/PostgresqlContainer.java
https://tools.hmcts.net/jira/browse/JS-290
Create juror_eric schema and voters_temp table
```
[ ] Yes
[x ] No
```
=> task/JS-293 Create juror_eric schema and voters_temp table

src/main/java/uk/gov/hmcts/juror/api/moj/service/DeferralResponseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/ExcusalResponseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-290
Juror Address was not updated before the deferral was processed on the summons response
```
[ ] Yes
[ x] No
```
=> Task/JS-290 Juror Address was not updated before the deferral was processed on the summons response

src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorDetailsResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java, src/main/resources/db/migrationv2/V2_59__alter_phone_number_combined.sql
https://tools.hmcts.net/jira/browse/JS-152
amend edit phone number logic 
```
[ ] Yes
[ x] No
```
=> JS-152 amend edit phone number logic

src/main/resources/db/migrationv2/V2_61__alter_pool_comments_user_id.sql
https://tools.hmcts.net/jira/browse/JS-286
alter table pool_comments.user_id
```
[ ] Yes
[ x] No
```
=> JS-286 alter table pool_comments user_id

charts/juror-api/Chart.yaml
=> helm: update to use oci

src/main/java/uk/gov/hmcts/juror/api/bureau/controller/BureauEndpointController.java, src/main/java/uk/gov/hmcts/juror/api/juror/service/ExcusedCompletedCourtCommsServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/EditJurorRecordRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorDetailsResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/response/JurorOverviewResponseDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/domain/Juror.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java, src/main/resources/db/migrationv2/V2_64__alter_juror_add_living_overseas_column.sql
add livivng overseas entity
https://tools.hmcts.net/jira/browse/JS-303
```
[ ] Yes
[x ] No
```
=> JS-303 add living overseas entity

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/DeferralMaintenanceControllerITest.java, src/integration-test/resources/db/DeferralMaintenance_MoveDeferredJurorTest.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/DeferralMaintenanceController.java, src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/DeferredJurorMoveRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/deferralmaintenance/ManageDeferralsServiceTest.java
https://tools.hmcts.net/jira/browse/JS-304
As a Bureau officer I am not able to choose another court when moving out of Deferral Maintenance
```
[ ] Yes
[x ] No
```
=> Task/JS-304 choose another court when moving out of Deferral Maintenance

src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-346
add business validation for a juror with the summoned status 
```
[ ] Yes
[ x] No
```
=> JS-346 Add business validation summoned juror status

src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java
non functional change
```
[ ] Yes
[x ] No
```
=> JS-296a non functional change

src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolQueries.java
fix issue not using correct template 
```
[ ] Yes
[ x] No
```
=> JS-299a fix issue in for test

src/main/java/uk/gov/hmcts/juror/api/moj/domain/TemporaryCourtPhone.java, src/main/resources/db/migrationv2/V2_71__update_notify_template_mapping_mapper.sql
Amend typo in notify_template_field.mapper_object
```
[ ] Yes
[x ] No
```
=> JS-299e amend typo

src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-294
>10 and >201 day counts incorrectly count NO SHOW days
```
[ x] Yes
[ ] No
```
=> Task/JS-294 >10 and >201 day counts incorrectly count NO SHOW days

src/main/java/uk/gov/hmcts/juror/api/moj/controller/JurorRecordController.java, src/main/java/uk/gov/hmcts/juror/api/moj/exception/MojException.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorRecordServiceImpl.java
Mark an undeliverable juror record  as summoned 
https://tools.hmcts.net/jira/browse/JS-210
[ ] Yes
[ ] No
```
=> JS-210 mark undeliverable to summoned

src/main/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/expense/JurorExpenseServiceTest.java
JS-383
Apply default expenses does not take into account travel time
```
[ ] Yes
[ x] No
```
=> task/JS-383 Apply default expenses does not take into account travel time

infrastructure/demo.tfvars
Updated Storage size on demo to match with Prod as requirement by the DLRM team
=> Update demo.tfvars - Changing storage size to match up as production

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/ExcusalResponseControllerITest.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/ExcusalResponseServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/summonsmanagement/JurorResponseService.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/ExcusalResponseServiceImplTest.java
https://tools.hmcts.net/jira/browse/JS-376
This is to revert the changes made for JS-376 as business do not want to go ahead with this
```
[ ] Yes
[ x] No
```
=> Revert "Task/JS-376"

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/DeferralRequestControllerITest.java, src/integration-test/resources/db/DeferralRequestController_createInitialPoolRecords.sql, src/integration-test/resources/db/DeferralRequestController_createPoolAndResponse.sql, src/main/java/uk/gov/hmcts/juror/api/moj/service/SummonsReplyStatusUpdateServiceImpl.java, src/test/java/uk/gov/hmcts/juror/api/moj/service/JurorManagementServiceImplTest.java
https://tools.hmcts.net/jira/browse/JS-402
Deferring into maintenance removes DOB from Juror Record
```
[ ] Yes
[ x] No
```
=> Task/JS-402 Deferring into maintenance removes DOB from Juror Record

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/CourtDashboardControllerITest.java, src/integration-test/resources/db/CourtDashboardAttendanceITest.sql, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepository.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IAppearanceRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/CourtDashboardServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/jurormanagement/JurorAppearanceServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-513
The 'not checked in' value on juror dashboard is showing a negative number
```
[ ] Yes
[ x] No
```
=> task/JS-513 The 'not checked in' on juror dashboard is showing a negative number

src/main/java/uk/gov/hmcts/juror/api/moj/domain/TemporaryCourtPhone.java
Updated Tauton court phone number 
https://tools.hmcts.net/jira/browse/JS-529
```
[ ] Yes
[ x] No
```
=> JS-529 update Taunton phone number

src/main/resources/db/migrationv2/V2_82__update_payment_files_to_clob_sp.sql
https://tools.hmcts.net/jira/browse/JS-340
update stored payment file stored procedure so it does not sequentially increment expense_file_name 
```
[ ] Yes
[ x] No
```
=> JS-340 update payment to clob sp

src/integration-test/java/uk/gov/hmcts/juror/api/moj/controller/CourtDashboardControllerITest.java, src/integration-test/resources/db/CourtDashboardAttendanceITest.sql, src/main/java/uk/gov/hmcts/juror/api/moj/controller/courtdashboard/CourtAttendanceInfoDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/JurorPoolRepositoryImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/CourtDashboardServiceImpl.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorPoolService.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/JurorPoolServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-532
As a court officer I want to add some additional information to the dashboard (BE) - 
Add the number of jurors on call for the court under unconfirmed attendance
```
[ x] Yes
[ ] No
```
=> task/JS-532 Adding jurors on call to Court dashboard

src/main/java/uk/gov/hmcts/juror/api/moj/controller/request/PoolSearchRequestDto.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/IPoolRequestSearchQueries.java, src/main/java/uk/gov/hmcts/juror/api/moj/repository/PoolRequestSearchQueries.java, src/main/java/uk/gov/hmcts/juror/api/moj/service/PoolRequestSearchServiceImpl.java
https://tools.hmcts.net/jira/browse/JS-227
Add Nil pool parameter to advanced search criteria
```
[ ] Yes
[x] No
```
=> JS-227 - Add Nil Pool search option

build.gradle
https://tools.hmcts.net/jira/browse/JS-565
update springDoc dependency to fix swagger 
```
[ ] Yes
[ x] No
```
=> JS-565 update springDoc dependency

Dockerfile, build.gradle
https://tools.hmcts.net/jira/browse/JS-558
Update juror-api with non breaking Renovate PRs
```
[ ] Yes
[ x] No
```
=> Task/JS-558 Merge Non-Breaking Renovate all API's PRs (BE)
